# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.query_guard_pubkey200_response import QueryGuardPubkey200Response


class TestQueryGuardPubkey200Response(unittest.TestCase):
    """QueryGuardPubkey200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> QueryGuardPubkey200Response:
        """Test QueryGuardPubkey200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `QueryGuardPubkey200Response`
        """
        model = QueryGuardPubkey200Response()
        if include_optional:
            return QueryGuardPubkey200Response(
                pubkey = '0111039d-27fb-49ba-b172-6e0aa80e37ec',
                status = 'New',
                addresses = [
                    cobo_waas2.models.query_guard_pubkey_200_response_addresses_inner.query_guard_pubkey_200_response_addresses_inner(
                        address = '0x0000000000000000000000000000000000000000', 
                        chain_id = 'ETH', )
                    ]
            )
        else:
            return QueryGuardPubkey200Response(
        )
        """

    def testQueryGuardPubkey200Response(self):
        """Test QueryGuardPubkey200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
