# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    The version of the OpenAPI document: 1.1.0
    Contact: support@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.transaction_utxo import TransactionUtxo


class TestTransactionUtxo(unittest.TestCase):
    """TransactionUtxo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TransactionUtxo:
        """Test TransactionUtxo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TransactionUtxo`
        """
        model = TransactionUtxo()
        if include_optional:
            return TransactionUtxo(
                tx_hash = '7014d7d9b91862d7131f7543d84da3bec60e20be93c23ad01167c48b778fdemo',
                vout_n = 0
            )
        else:
            return TransactionUtxo(
        )
        """

    def testTransactionUtxo(self):
        """Test TransactionUtxo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
