# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.check_address_chains_validity200_response_inner import CheckAddressChainsValidity200ResponseInner


class TestCheckAddressChainsValidity200ResponseInner(unittest.TestCase):
    """CheckAddressChainsValidity200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CheckAddressChainsValidity200ResponseInner:
        """Test CheckAddressChainsValidity200ResponseInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CheckAddressChainsValidity200ResponseInner`
        """
        model = CheckAddressChainsValidity200ResponseInner()
        if include_optional:
            return CheckAddressChainsValidity200ResponseInner(
                chain_id = 'ETH',
                validity = True
            )
        else:
            return CheckAddressChainsValidity200ResponseInner(
                chain_id = 'ETH',
                validity = True,
        )
        """

    def testCheckAddressChainsValidity200ResponseInner(self):
        """Test CheckAddressChainsValidity200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
