# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.key_share_holder_type import KeyShareHolderType


class TestKeyShareHolderType(unittest.TestCase):
    """KeyShareHolderType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testKeyShareHolderType(self):
        """Test KeyShareHolderType"""
        # inst = KeyShareHolderType()


if __name__ == '__main__':
    unittest.main()
