# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.payment_bulk_send_item_status import PaymentBulkSendItemStatus


class TestPaymentBulkSendItemStatus(unittest.TestCase):
    """PaymentBulkSendItemStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaymentBulkSendItemStatus(self):
        """Test PaymentBulkSendItemStatus"""
        # inst = PaymentBulkSendItemStatus()


if __name__ == '__main__':
    unittest.main()
