# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.update_destination_by_id_request import UpdateDestinationByIdRequest


class TestUpdateDestinationByIdRequest(unittest.TestCase):
    """UpdateDestinationByIdRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateDestinationByIdRequest:
        """Test UpdateDestinationByIdRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateDestinationByIdRequest`
        """
        model = UpdateDestinationByIdRequest()
        if include_optional:
            return UpdateDestinationByIdRequest(
                destination_name = 'Destination A',
                destination_type = 'Individual',
                merchant_id = 'M1001',
                country = 'USA',
                email = 'destination@example.com',
                contact_address = '123 Main St, Anytown, USA'
            )
        else:
            return UpdateDestinationByIdRequest(
                destination_name = 'Destination A',
                destination_type = 'Individual',
        )
        """

    def testUpdateDestinationByIdRequest(self):
        """Test UpdateDestinationByIdRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
