# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.payment_estimate_fee import PaymentEstimateFee


class TestPaymentEstimateFee(unittest.TestCase):
    """PaymentEstimateFee unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentEstimateFee:
        """Test PaymentEstimateFee
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentEstimateFee`
        """
        model = PaymentEstimateFee()
        if include_optional:
            return PaymentEstimateFee(
                token_id = '',
                amount = '500.00'
            )
        else:
            return PaymentEstimateFee(
                token_id = '',
                amount = '500.00',
        )
        """

    def testPaymentEstimateFee(self):
        """Test PaymentEstimateFee"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
