# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.get_counterparty_entry200_response import GetCounterpartyEntry200Response


class TestGetCounterpartyEntry200Response(unittest.TestCase):
    """GetCounterpartyEntry200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetCounterpartyEntry200Response:
        """Test GetCounterpartyEntry200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetCounterpartyEntry200Response`
        """
        model = GetCounterpartyEntry200Response()
        if include_optional:
            return GetCounterpartyEntry200Response(
                wallet_address = cobo_waas2.models.wallet_address.WalletAddress(
                    wallet_address_id = '123e4567-e89b-12d3-a456-426614174003', 
                    address = '0x1234567890abcdef...', 
                    chain_id = 'TRON', 
                    risk_level = 'Low', 
                    screening_timestamp = 1744689600, 
                    updated_timestamp = 1744689600, )
            )
        else:
            return GetCounterpartyEntry200Response(
        )
        """

    def testGetCounterpartyEntry200Response(self):
        """Test GetCounterpartyEntry200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
