# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.tokenization_erc20_fund_token_params import TokenizationERC20FundTokenParams


class TestTokenizationERC20FundTokenParams(unittest.TestCase):
    """TokenizationERC20FundTokenParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TokenizationERC20FundTokenParams:
        """Test TokenizationERC20FundTokenParams
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TokenizationERC20FundTokenParams`
        """
        model = TokenizationERC20FundTokenParams()
        if include_optional:
            return TokenizationERC20FundTokenParams(
                standard = 'ERC20',
                name = 'Global Equity Fund',
                symbol = 'GEF',
                asset_token = '0x4922a015c4407F87432B179bb209e125432E4a2A',
                initial_nav = '1.0',
                initial_annual_rate = '0',
                min_deposit = '0',
                min_redemption = '0',
                max_annual_rate = '115792089237316195423570985008687907853269984665640564039457584007913129639935',
                max_rate_change = '115792089237316195423570985008687907853269984665640564039457584007913129639935',
                min_update_interval_seconds = 86400,
                decimals = 18,
                permissions = cobo_waas2.models.tokenization_erc20_fund_token_permission_params.TokenizationERC20FundTokenPermissionParams(
                    owner = ["0x1234567890abcdef1234567890abcdef12345678"], 
                    manager = ["0xabcdefabcdefabcdefabcdefabcdefabcdefabcd"], 
                    nav_updater = ["0x2345678901bcdef2345678901bcdef234567890"], 
                    redemption_approver = ["0x3456789012cdef3456789012cdef34567890123"], 
                    settlement_operator = ["0x4567890123def4567890123def456789012345"], 
                    emergency_guardian = ["0x567890124ef567890124ef5678901234567"], )
            )
        else:
            return TokenizationERC20FundTokenParams(
                standard = 'ERC20',
                name = 'Global Equity Fund',
                symbol = 'GEF',
                asset_token = '0x4922a015c4407F87432B179bb209e125432E4a2A',
        )
        """

    def testTokenizationERC20FundTokenParams(self):
        """Test TokenizationERC20FundTokenParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
