# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.allocation_item_status import AllocationItemStatus


class TestAllocationItemStatus(unittest.TestCase):
    """AllocationItemStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAllocationItemStatus(self):
        """Test AllocationItemStatus"""
        # inst = AllocationItemStatus()


if __name__ == '__main__':
    unittest.main()
