# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.list_subscription_plans200_response import ListSubscriptionPlans200Response


class TestListSubscriptionPlans200Response(unittest.TestCase):
    """ListSubscriptionPlans200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListSubscriptionPlans200Response:
        """Test ListSubscriptionPlans200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListSubscriptionPlans200Response`
        """
        model = ListSubscriptionPlans200Response()
        if include_optional:
            return ListSubscriptionPlans200Response(
                data = [
                    cobo_waas2.models.payment_subscription_plan.PaymentSubscriptionPlan(
                        plan_id = '123e457-e89b-12d3-a456-426614174004', 
                        developer_plan_id = '123e457-e89b-12d3-a456-426614174004', 
                        period_type = 'Yearly', 
                        periods = 12, 
                        interval = 2592000, 
                        trial_period = 604800, 
                        amount = '500.00', 
                        token_id = 'ETH_USDT', 
                        currency = 'USD', )
                    ],
                pagination = cobo_waas2.models.pagination.Pagination(
                    before = 'RqeEoTkgKG5rpzqYzg2Hd3szmPoj2cE7w5jWwShz3C1vyGmk1', 
                    after = 'RqeEoTkgKG5rpzqYzg2Hd3szmPoj2cE7w5jWwShz3C1vyGSAk', 
                    total_count = 10000, )
            )
        else:
            return ListSubscriptionPlans200Response(
        )
        """

    def testListSubscriptionPlans200Response(self):
        """Test ListSubscriptionPlans200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
