# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.bank_account_payment_method import BankAccountPaymentMethod


class TestBankAccountPaymentMethod(unittest.TestCase):
    """BankAccountPaymentMethod unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBankAccountPaymentMethod(self):
        """Test BankAccountPaymentMethod"""
        # inst = BankAccountPaymentMethod()


if __name__ == '__main__':
    unittest.main()
