# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    The version of the OpenAPI document: 1.0.0
    Contact: support@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.transaction_type import TransactionType


class TestTransactionType(unittest.TestCase):
    """TransactionType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTransactionType(self):
        """Test TransactionType"""
        # inst = TransactionType()


if __name__ == '__main__':
    unittest.main()
