# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.fee_station_check_fee_station_usage_response import FeeStationCheckFeeStationUsageResponse


class TestFeeStationCheckFeeStationUsageResponse(unittest.TestCase):
    """FeeStationCheckFeeStationUsageResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FeeStationCheckFeeStationUsageResponse:
        """Test FeeStationCheckFeeStationUsageResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FeeStationCheckFeeStationUsageResponse`
        """
        model = FeeStationCheckFeeStationUsageResponse()
        if include_optional:
            return FeeStationCheckFeeStationUsageResponse(
                token_id = 'ETH',
                gas_station_type = 'CoboOperationStation',
                is_fee_station_applicable = True,
                is_balance_sufficient = False,
                balance = '0.0021',
                total_fee_amount = '0.0021',
                is_sponsor_applicable = True,
                sponsored_fee_amount = '0.0021'
            )
        else:
            return FeeStationCheckFeeStationUsageResponse(
                token_id = 'ETH',
                gas_station_type = 'CoboOperationStation',
                is_fee_station_applicable = True,
                is_balance_sufficient = False,
                balance = '0.0021',
                total_fee_amount = '0.0021',
                is_sponsor_applicable = True,
                sponsored_fee_amount = '0.0021',
        )
        """

    def testFeeStationCheckFeeStationUsageResponse(self):
        """Test FeeStationCheckFeeStationUsageResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
