# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.tss_callback_action_type import TSSCallbackActionType


class TestTSSCallbackActionType(unittest.TestCase):
    """TSSCallbackActionType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTSSCallbackActionType(self):
        """Test TSSCallbackActionType"""
        # inst = TSSCallbackActionType()


if __name__ == '__main__':
    unittest.main()
