# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.kyt_screenings_decisions_type import KytScreeningsDecisionsType


class TestKytScreeningsDecisionsType(unittest.TestCase):
    """KytScreeningsDecisionsType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testKytScreeningsDecisionsType(self):
        """Test KytScreeningsDecisionsType"""
        # inst = KytScreeningsDecisionsType()


if __name__ == '__main__':
    unittest.main()
