# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.payout_detail import PayoutDetail


class TestPayoutDetail(unittest.TestCase):
    """PayoutDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PayoutDetail:
        """Test PayoutDetail
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PayoutDetail`
        """
        model = PayoutDetail()
        if include_optional:
            return PayoutDetail(
                payout_id = '123e4567-e89b-12d3-a456-426614174003',
                source = cobo_waas2.models.payout_source.PayoutSource(
                    wallet_id = '123e4567-e89b-12d3-a456-426614174003', 
                    address = '0xabc123def456ghi789jkl012mno345pqr678stu901', ),
                destination_count = 10,
                token_id = '123e4567-e89b-12d3-a456-426614174003',
                total_amount = '1.500000',
                status = 'None',
                description = 'Monthly vendor payments - January 2024',
                created_timestamp = 1744689600,
                updated_timestamp = 1744689600,
                destinations = [
                    null
                    ]
            )
        else:
            return PayoutDetail(
                payout_id = '123e4567-e89b-12d3-a456-426614174003',
                destination_count = 10,
                token_id = '123e4567-e89b-12d3-a456-426614174003',
                total_amount = '1.500000',
                status = 'None',
                created_timestamp = 1744689600,
        )
        """

    def testPayoutDetail(self):
        """Test PayoutDetail"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
