# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    The version of the OpenAPI document: 1.1.0
    Contact: support@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.transaction_status import TransactionStatus


class TestTransactionStatus(unittest.TestCase):
    """TransactionStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTransactionStatus(self):
        """Test TransactionStatus"""
        # inst = TransactionStatus()


if __name__ == '__main__':
    unittest.main()
