# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.create_counterparty_entry_request import CreateCounterpartyEntryRequest


class TestCreateCounterpartyEntryRequest(unittest.TestCase):
    """CreateCounterpartyEntryRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateCounterpartyEntryRequest:
        """Test CreateCounterpartyEntryRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateCounterpartyEntryRequest`
        """
        model = CreateCounterpartyEntryRequest()
        if include_optional:
            return CreateCounterpartyEntryRequest(
                counterparty_id = '123e4567-e89b-12d3-a456-426614174003',
                wallet_addresses = [
                    cobo_waas2.models.create_wallet_address.CreateWalletAddress(
                        address = '0x1234567890abcdef...', 
                        chain_id = 'TRON', )
                    ]
            )
        else:
            return CreateCounterpartyEntryRequest(
                counterparty_id = '123e4567-e89b-12d3-a456-426614174003',
        )
        """

    def testCreateCounterpartyEntryRequest(self):
        """Test CreateCounterpartyEntryRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
