# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.curve_type import CurveType


class TestCurveType(unittest.TestCase):
    """CurveType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCurveType(self):
        """Test CurveType"""
        # inst = CurveType()


if __name__ == '__main__':
    unittest.main()
