# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.estimated_fil_fee import EstimatedFILFee


class TestEstimatedFILFee(unittest.TestCase):
    """EstimatedFILFee unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EstimatedFILFee:
        """Test EstimatedFILFee
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EstimatedFILFee`
        """
        model = EstimatedFILFee()
        if include_optional:
            return EstimatedFILFee(
                fee_type = 'EVM_EIP_1559',
                token_id = 'ETH',
                slow = None,
                recommended = None,
                fast = None
            )
        else:
            return EstimatedFILFee(
                fee_type = 'EVM_EIP_1559',
                token_id = 'ETH',
                recommended = None,
        )
        """

    def testEstimatedFILFee(self):
        """Test EstimatedFILFee"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
