# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.payment_bulk_send_item import PaymentBulkSendItem


class TestPaymentBulkSendItem(unittest.TestCase):
    """PaymentBulkSendItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentBulkSendItem:
        """Test PaymentBulkSendItem
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentBulkSendItem`
        """
        model = PaymentBulkSendItem()
        if include_optional:
            return PaymentBulkSendItem(
                bulk_send_item_id = '123e4567-e89b-12d3-a456-426614174003',
                token_id = 'ETH_USDT',
                receiving_address = '0xabc123456789def0000000000000000000000000',
                amount = '500.00',
                description = 'Invoice #INV-2024-001',
                status = 'Pending',
                validation_status = 'Pending'
            )
        else:
            return PaymentBulkSendItem(
                bulk_send_item_id = '123e4567-e89b-12d3-a456-426614174003',
                token_id = 'ETH_USDT',
                receiving_address = '0xabc123456789def0000000000000000000000000',
                amount = '500.00',
                status = 'Pending',
                validation_status = 'Pending',
        )
        """

    def testPaymentBulkSendItem(self):
        """Test PaymentBulkSendItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
