# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.tokenization_burn_token_params import TokenizationBurnTokenParams


class TestTokenizationBurnTokenParams(unittest.TestCase):
    """TokenizationBurnTokenParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TokenizationBurnTokenParams:
        """Test TokenizationBurnTokenParams
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TokenizationBurnTokenParams`
        """
        model = TokenizationBurnTokenParams()
        if include_optional:
            return TokenizationBurnTokenParams(
                source = None,
                burns = [
                    cobo_waas2.models.tokenization_burn_token_params_burns_inner.TokenizationBurnTokenParams_burns_inner(
                        amount = '0.99', 
                        from_address = '0x051A924H4dCb264226d7B036C2893a0D344', )
                    ]
            )
        else:
            return TokenizationBurnTokenParams(
                source = None,
                burns = [
                    cobo_waas2.models.tokenization_burn_token_params_burns_inner.TokenizationBurnTokenParams_burns_inner(
                        amount = '0.99', 
                        from_address = '0x051A924H4dCb264226d7B036C2893a0D344', )
                    ],
        )
        """

    def testTokenizationBurnTokenParams(self):
        """Test TokenizationBurnTokenParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
