# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.create_settlement import CreateSettlement


class TestCreateSettlement(unittest.TestCase):
    """CreateSettlement unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateSettlement:
        """Test CreateSettlement
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateSettlement`
        """
        model = CreateSettlement()
        if include_optional:
            return CreateSettlement(
                merchant_id = 'M1001',
                token_id = 'ETH_USDT',
                currency = 'USD',
                amount = '500.00',
                bank_account_id = '0123e457-e89b-12d3-a456-426614174004',
                settlement_type = 'Merchant'
            )
        else:
            return CreateSettlement(
                amount = '500.00',
                bank_account_id = '0123e457-e89b-12d3-a456-426614174004',
        )
        """

    def testCreateSettlement(self):
        """Test CreateSettlement"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
