# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.fee_station_transfer import FeeStationTransfer


class TestFeeStationTransfer(unittest.TestCase):
    """FeeStationTransfer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FeeStationTransfer:
        """Test FeeStationTransfer
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FeeStationTransfer`
        """
        model = FeeStationTransfer()
        if include_optional:
            return FeeStationTransfer(
                token_id = 'ETH_USDT',
                destination = cobo_waas2.models.fee_station_destination.FeeStationDestination(
                    address = '19AR6YWEGbSoY8UT9Ksy9WrmrZPD5sL4Ku', 
                    memo = '82840924', 
                    amount = '1.5', )
            )
        else:
            return FeeStationTransfer(
                token_id = 'ETH_USDT',
        )
        """

    def testFeeStationTransfer(self):
        """Test FeeStationTransfer"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
