# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.create_address_books_param import CreateAddressBooksParam


class TestCreateAddressBooksParam(unittest.TestCase):
    """CreateAddressBooksParam unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateAddressBooksParam:
        """Test CreateAddressBooksParam
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateAddressBooksParam`
        """
        model = CreateAddressBooksParam()
        if include_optional:
            return CreateAddressBooksParam(
                address_books = [
                    cobo_waas2.models.create_address_book.Create Address Book(
                        chain_ids = [
                            'ETH'
                            ], 
                        address = '0x570f02f2b5fcf3ac56fb6703bd7039c0c9e33460', 
                        memo = '9d4773eb', 
                        label = 'test', 
                        email = 'help@cobo.com', )
                    ]
            )
        else:
            return CreateAddressBooksParam(
                address_books = [
                    cobo_waas2.models.create_address_book.Create Address Book(
                        chain_ids = [
                            'ETH'
                            ], 
                        address = '0x570f02f2b5fcf3ac56fb6703bd7039c0c9e33460', 
                        memo = '9d4773eb', 
                        label = 'test', 
                        email = 'help@cobo.com', )
                    ],
        )
        """

    def testCreateAddressBooksParam(self):
        """Test CreateAddressBooksParam"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
