# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.list_counterparties200_response import ListCounterparties200Response


class TestListCounterparties200Response(unittest.TestCase):
    """ListCounterparties200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListCounterparties200Response:
        """Test ListCounterparties200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListCounterparties200Response`
        """
        model = ListCounterparties200Response()
        if include_optional:
            return ListCounterparties200Response(
                data = [
                    cobo_waas2.models.counterparty.Counterparty(
                        counterparty_id = '123e4567-e89b-12d3-a456-426614174003', 
                        counterparty_type = 'Individual', 
                        counterparty_name = 'Counterparty A', 
                        country = 'USA', 
                        email = 'counterparty@example.com', 
                        contact_address = '123 Main St, Anytown, USA', 
                        created_timestamp = 1744689600, 
                        updated_timestamp = 1744689600, )
                    ],
                pagination = cobo_waas2.models.pagination.Pagination(
                    before = 'RqeEoTkgKG5rpzqYzg2Hd3szmPoj2cE7w5jWwShz3C1vyGmk1', 
                    after = 'RqeEoTkgKG5rpzqYzg2Hd3szmPoj2cE7w5jWwShz3C1vyGSAk', 
                    total_count = 10000, )
            )
        else:
            return ListCounterparties200Response(
        )
        """

    def testListCounterparties200Response(self):
        """Test ListCounterparties200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
