# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.policy_action import PolicyAction


class TestPolicyAction(unittest.TestCase):
    """PolicyAction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PolicyAction:
        """Test PolicyAction
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PolicyAction`
        """
        model = PolicyAction()
        if include_optional:
            return PolicyAction(
                action_type = 'Pending',
                content = cobo_waas2.models.policy_action_content.PolicyAction_content(
                    type = 'PART_APPROVAL', 
                    roles = [
                        'admin'
                        ], 
                    user_ids = [
                        'f47ac10b-58cc-4372-a567-0e02b2c3d479'
                        ], 
                    threshold = 15, )
            )
        else:
            return PolicyAction(
                action_type = 'Pending',
        )
        """

    def testPolicyAction(self):
        """Test PolicyAction"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
