# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: support@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.transaction_sub_status import TransactionSubStatus


class TestTransactionSubStatus(unittest.TestCase):
    """TransactionSubStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTransactionSubStatus(self):
        """Test TransactionSubStatus"""
        # inst = TransactionSubStatus()


if __name__ == '__main__':
    unittest.main()
