# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.check_addresses_validity200_response_inner import CheckAddressesValidity200ResponseInner


class TestCheckAddressesValidity200ResponseInner(unittest.TestCase):
    """CheckAddressesValidity200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CheckAddressesValidity200ResponseInner:
        """Test CheckAddressesValidity200ResponseInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CheckAddressesValidity200ResponseInner`
        """
        model = CheckAddressesValidity200ResponseInner()
        if include_optional:
            return CheckAddressesValidity200ResponseInner(
                address = '0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045',
                validity = True
            )
        else:
            return CheckAddressesValidity200ResponseInner(
                address = '0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045',
                validity = True,
        )
        """

    def testCheckAddressesValidity200ResponseInner(self):
        """Test CheckAddressesValidity200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
