# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.chains_event_data import ChainsEventData


class TestChainsEventData(unittest.TestCase):
    """ChainsEventData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChainsEventData:
        """Test ChainsEventData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChainsEventData`
        """
        model = ChainsEventData()
        if include_optional:
            return ChainsEventData(
                data_type = 'Transaction',
                chains = [
                    cobo_waas2.models.chain_info.ChainInfo(
                        chain_id = 'ETH', 
                        symbol = 'ETH', 
                        icon_url = 'https://d.cobo.com/public/logos/ETH.png', 
                        explorer_tx_url = 'https://etherscan.io/tx/{txn_id}', 
                        explorer_address_url = 'https://etherscan.io/address/{address}', 
                        require_memo = False, 
                        confirming_threshold = 15, 
                        coinbase_maturity = 15, )
                    ],
                wallet_type = 'Custodial',
                wallet_subtypes = [
                    'Asset'
                    ]
            )
        else:
            return ChainsEventData(
                data_type = 'Transaction',
                chains = [
                    cobo_waas2.models.chain_info.ChainInfo(
                        chain_id = 'ETH', 
                        symbol = 'ETH', 
                        icon_url = 'https://d.cobo.com/public/logos/ETH.png', 
                        explorer_tx_url = 'https://etherscan.io/tx/{txn_id}', 
                        explorer_address_url = 'https://etherscan.io/address/{address}', 
                        require_memo = False, 
                        confirming_threshold = 15, 
                        coinbase_maturity = 15, )
                    ],
        )
        """

    def testChainsEventData(self):
        """Test ChainsEventData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
