# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.compliance_kyt_screenings_update_event_data import ComplianceKytScreeningsUpdateEventData


class TestComplianceKytScreeningsUpdateEventData(unittest.TestCase):
    """ComplianceKytScreeningsUpdateEventData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ComplianceKytScreeningsUpdateEventData:
        """Test ComplianceKytScreeningsUpdateEventData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ComplianceKytScreeningsUpdateEventData`
        """
        model = ComplianceKytScreeningsUpdateEventData()
        if include_optional:
            return ComplianceKytScreeningsUpdateEventData(
                data_type = 'Transaction',
                transaction_id = 'aff0e1cb-15b2-4e1f-9b9d-a9133715986f',
                transaction_type = 'Deposit',
                review_status = 'PendingScreening',
                funds_status = 'Frozen',
                updated_timestamp = 1610445878970
            )
        else:
            return ComplianceKytScreeningsUpdateEventData(
                data_type = 'Transaction',
                transaction_id = 'aff0e1cb-15b2-4e1f-9b9d-a9133715986f',
                transaction_type = 'Deposit',
                review_status = 'PendingScreening',
                funds_status = 'Frozen',
                updated_timestamp = 1610445878970,
        )
        """

    def testComplianceKytScreeningsUpdateEventData(self):
        """Test ComplianceKytScreeningsUpdateEventData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
