# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    The version of the OpenAPI document: 1.1.0
    Contact: support@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.lock_utxos201_response import LockUtxos201Response


class TestLockUtxos201Response(unittest.TestCase):
    """LockUtxos201Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LockUtxos201Response:
        """Test LockUtxos201Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LockUtxos201Response`
        """
        model = LockUtxos201Response()
        if include_optional:
            return LockUtxos201Response(
                executed = True
            )
        else:
            return LockUtxos201Response(
        )
        """

    def testLockUtxos201Response(self):
        """Test LockUtxos201Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
