# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.tss_callback_response import TSSCallbackResponse


class TestTSSCallbackResponse(unittest.TestCase):
    """TSSCallbackResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TSSCallbackResponse:
        """Test TSSCallbackResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TSSCallbackResponse`
        """
        model = TSSCallbackResponse()
        if include_optional:
            return TSSCallbackResponse(
                request_id = '20231213122855000000000000000000:1',
                status = 0,
                action = 'APPROVE',
                error = 'internal error'
            )
        else:
            return TSSCallbackResponse(
        )
        """

    def testTSSCallbackResponse(self):
        """Test TSSCallbackResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
