# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.payment_balance_flow_direction import PaymentBalanceFlowDirection


class TestPaymentBalanceFlowDirection(unittest.TestCase):
    """PaymentBalanceFlowDirection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaymentBalanceFlowDirection(self):
        """Test PaymentBalanceFlowDirection"""
        # inst = PaymentBalanceFlowDirection()


if __name__ == '__main__':
    unittest.main()
