# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.list_batch_allocations200_response import ListBatchAllocations200Response


class TestListBatchAllocations200Response(unittest.TestCase):
    """ListBatchAllocations200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListBatchAllocations200Response:
        """Test ListBatchAllocations200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListBatchAllocations200Response`
        """
        model = ListBatchAllocations200Response()
        if include_optional:
            return ListBatchAllocations200Response(
                data = [
                    cobo_waas2.models.batch_allocation.BatchAllocation(
                        batch_allocation_id = '123e457-e89b-12d3-a456-426614174004', 
                        request_id = '123e457-e89b-12d3-a456-426614174004', 
                        allocation_requests = [
                            cobo_waas2.models.allocation_request.AllocationRequest(
                                token_id = 'ETH_USDT', 
                                amount = '500.00', 
                                source_account = 'M1001', 
                                destination_account = 'M1001', 
                                description = 'Allocation for merchant M1001', )
                            ], 
                        initiator = 'b2ae1b5aaade686c968ef2bbd31cc75ba94e5a85fd9cb0b35b81dcc15f520e9d', 
                        created_timestamp = 1744689600, 
                        updated_timestamp = 1744689600, )
                    ],
                pagination = cobo_waas2.models.pagination.Pagination(
                    before = 'RqeEoTkgKG5rpzqYzg2Hd3szmPoj2cE7w5jWwShz3C1vyGmk1', 
                    after = 'RqeEoTkgKG5rpzqYzg2Hd3szmPoj2cE7w5jWwShz3C1vyGSAk', 
                    total_count = 10000, )
            )
        else:
            return ListBatchAllocations200Response(
        )
        """

    def testListBatchAllocations200Response(self):
        """Test ListBatchAllocations200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
