# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.order_address_info import OrderAddressInfo


class TestOrderAddressInfo(unittest.TestCase):
    """OrderAddressInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrderAddressInfo:
        """Test OrderAddressInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrderAddressInfo`
        """
        model = OrderAddressInfo()
        if include_optional:
            return OrderAddressInfo(
                wallet_id = '123e4567-e89b-12d3-a456-426614174001',
                amount = '0.000001',
                created_timestamp = 1744689600,
                updated_timestamp = 1744689600
            )
        else:
            return OrderAddressInfo(
                wallet_id = '123e4567-e89b-12d3-a456-426614174001',
                amount = '0.000001',
                created_timestamp = 1744689600,
                updated_timestamp = 1744689600,
        )
        """

    def testOrderAddressInfo(self):
        """Test OrderAddressInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
