# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: support@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.babylon_validator import BabylonValidator


class TestBabylonValidator(unittest.TestCase):
    """BabylonValidator unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BabylonValidator:
        """Test BabylonValidator
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BabylonValidator`
        """
        model = BabylonValidator()
        if include_optional:
            return BabylonValidator(
                icon_url = 'https://example.com/icon.png',
                name = 'Cobo',
                priority = 0,
                public_key = 'eca1b104dce16c30705f4147a9c4a373ac88646c5d1bcda6a89c018940cb96a0',
                commission_rate = 0.1,
                supported_pos_chains = ["Babylon","Cosmos"]
            )
        else:
            return BabylonValidator(
                icon_url = 'https://example.com/icon.png',
                name = 'Cobo',
                public_key = 'eca1b104dce16c30705f4147a9c4a373ac88646c5d1bcda6a89c018940cb96a0',
                commission_rate = 0.1,
                supported_pos_chains = ["Babylon","Cosmos"],
        )
        """

    def testBabylonValidator(self):
        """Test BabylonValidator"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
