# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.tss_signatures import TSSSignatures


class TestTSSSignatures(unittest.TestCase):
    """TSSSignatures unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TSSSignatures:
        """Test TSSSignatures
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TSSSignatures`
        """
        model = TSSSignatures()
        if include_optional:
            return TSSSignatures(
                signatures = [
                    cobo_waas2.models.tss_signature.TSSSignature(
                        bip32_path = 'm/44/0/2/0/0', 
                        msg_hash = '0x10ED43C718714eb63d5aA57B78B54704E256024EFFFFFFFFFFFFFFFFFFFFFFFF', 
                        tweak = '0x00', 
                        signature = '0x10ED43C718714eb63d5aA57B78B54704E256024EFFFFFFFFFFFFFFFFFFFFFFFF', 
                        signature_recovery = '0x00', )
                    ],
                signature_type = 1,
                tss_protocol = 1
            )
        else:
            return TSSSignatures(
        )
        """

    def testTSSSignatures(self):
        """Test TSSSignatures"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
