# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.travel_rule_deposit_legal_entity import TravelRuleDepositLegalEntity


class TestTravelRuleDepositLegalEntity(unittest.TestCase):
    """TravelRuleDepositLegalEntity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TravelRuleDepositLegalEntity:
        """Test TravelRuleDepositLegalEntity
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TravelRuleDepositLegalEntity`
        """
        model = TravelRuleDepositLegalEntity()
        if include_optional:
            return TravelRuleDepositLegalEntity(
                selected_entity_type = 'LEGAL',
                legal_name = 'Company ABC Ltd.',
                date_of_incorporation = 'Thu May 20 00:00:00 UTC 2010',
                place_of_incorporation = 'City, Country'
            )
        else:
            return TravelRuleDepositLegalEntity(
                selected_entity_type = 'LEGAL',
                legal_name = 'Company ABC Ltd.',
        )
        """

    def testTravelRuleDepositLegalEntity(self):
        """Test TravelRuleDepositLegalEntity"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
