# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.query_approval_statement200_response import QueryApprovalStatement200Response


class TestQueryApprovalStatement200Response(unittest.TestCase):
    """QueryApprovalStatement200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> QueryApprovalStatement200Response:
        """Test QueryApprovalStatement200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `QueryApprovalStatement200Response`
        """
        model = QueryApprovalStatement200Response()
        if include_optional:
            return QueryApprovalStatement200Response(
                id = '168108513539918',
                user_id = '168108513539918',
                pubkey = '96db1b3c68c3a3497bffb7e257a3900b0e86575c968a346a6696d1676fa8c5a6431b46c867134bd5fb8a9b5f787fa0c534d7c7664f1e52c432ce64326cc4cc1d',
                status = 'New'
            )
        else:
            return QueryApprovalStatement200Response(
        )
        """

    def testQueryApprovalStatement200Response(self):
        """Test QueryApprovalStatement200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
