# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    The version of the OpenAPI document: 1.0.0
    Contact: support@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.smart_contract_wallet_operation_type import SmartContractWalletOperationType


class TestSmartContractWalletOperationType(unittest.TestCase):
    """SmartContractWalletOperationType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSmartContractWalletOperationType(self):
        """Test SmartContractWalletOperationType"""
        # inst = SmartContractWalletOperationType()


if __name__ == '__main__':
    unittest.main()
