# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.forced_sweep import ForcedSweep


class TestForcedSweep(unittest.TestCase):
    """ForcedSweep unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ForcedSweep:
        """Test ForcedSweep
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ForcedSweep`
        """
        model = ForcedSweep()
        if include_optional:
            return ForcedSweep(
                forced_sweep_id = 'aff0e1cb-15b2-4e1f-9b9d-a9133715986f',
                request_id = '123e4567-e89b-12d3-a456-426614174002',
                wallet_id = 'f47ac10b-58cc-4372-a567-0e02b2c3d479',
                token_id = 'ETH_USDT',
                amount = '10.5',
                status = 'Pending',
                created_timestamp = 1744689600,
                updated_timestamp = 1744689600
            )
        else:
            return ForcedSweep(
                forced_sweep_id = 'aff0e1cb-15b2-4e1f-9b9d-a9133715986f',
                request_id = '123e4567-e89b-12d3-a456-426614174002',
                status = 'Pending',
        )
        """

    def testForcedSweep(self):
        """Test ForcedSweep"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
