# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.create_token_listing_request_request import CreateTokenListingRequestRequest


class TestCreateTokenListingRequestRequest(unittest.TestCase):
    """CreateTokenListingRequestRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateTokenListingRequestRequest:
        """Test CreateTokenListingRequestRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateTokenListingRequestRequest`
        """
        model = CreateTokenListingRequestRequest()
        if include_optional:
            return CreateTokenListingRequestRequest(
                wallet_type = 'Custodial',
                wallet_subtype = 'Asset',
                chain_id = 'ETH',
                contract_address = '0x6B175474E89094C44Da98b954EedeAC495271d0F'
            )
        else:
            return CreateTokenListingRequestRequest(
                wallet_type = 'Custodial',
                wallet_subtype = 'Asset',
                chain_id = 'ETH',
                contract_address = '0x6B175474E89094C44Da98b954EedeAC495271d0F',
        )
        """

    def testCreateTokenListingRequestRequest(self):
        """Test CreateTokenListingRequestRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
