# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.create_swap_quote_request import CreateSwapQuoteRequest


class TestCreateSwapQuoteRequest(unittest.TestCase):
    """CreateSwapQuoteRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateSwapQuoteRequest:
        """Test CreateSwapQuoteRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateSwapQuoteRequest`
        """
        model = CreateSwapQuoteRequest()
        if include_optional:
            return CreateSwapQuoteRequest(
                wallet_id = '123e4567-e89b-12d3-a456-426614174000',
                pay_token_id = 'BTC',
                receive_token_id = 'ETH_WBTC',
                pay_amount = '100',
                receive_amount = '100'
            )
        else:
            return CreateSwapQuoteRequest(
                wallet_id = '123e4567-e89b-12d3-a456-426614174000',
                pay_token_id = 'BTC',
                receive_token_id = 'ETH_WBTC',
        )
        """

    def testCreateSwapQuoteRequest(self):
        """Test CreateSwapQuoteRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
