# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.tss_signature import TSSSignature


class TestTSSSignature(unittest.TestCase):
    """TSSSignature unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TSSSignature:
        """Test TSSSignature
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TSSSignature`
        """
        model = TSSSignature()
        if include_optional:
            return TSSSignature(
                bip32_path = 'm/44/0/2/0/0',
                msg_hash = '0x10ED43C718714eb63d5aA57B78B54704E256024EFFFFFFFFFFFFFFFFFFFFFFFF',
                tweak = '0x00',
                signature = '0x10ED43C718714eb63d5aA57B78B54704E256024EFFFFFFFFFFFFFFFFFFFFFFFF',
                signature_recovery = '0x00'
            )
        else:
            return TSSSignature(
        )
        """

    def testTSSSignature(self):
        """Test TSSSignature"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
