# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.transaction_block_info import TransactionBlockInfo


class TestTransactionBlockInfo(unittest.TestCase):
    """TransactionBlockInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TransactionBlockInfo:
        """Test TransactionBlockInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TransactionBlockInfo`
        """
        model = TransactionBlockInfo()
        if include_optional:
            return TransactionBlockInfo(
                block_number = 123,
                block_timestamp = 1717740319,
                block_hash = '0xc9ee947f8bb6027c161888bf0d004bec05e7c2beec7e6b187dc512174e438735'
            )
        else:
            return TransactionBlockInfo(
        )
        """

    def testTransactionBlockInfo(self):
        """Test TransactionBlockInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
