# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.tokenization_allowlist_activation_params import TokenizationAllowlistActivationParams


class TestTokenizationAllowlistActivationParams(unittest.TestCase):
    """TokenizationAllowlistActivationParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TokenizationAllowlistActivationParams:
        """Test TokenizationAllowlistActivationParams
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TokenizationAllowlistActivationParams`
        """
        model = TokenizationAllowlistActivationParams()
        if include_optional:
            return TokenizationAllowlistActivationParams(
                source = None,
                activation = True
            )
        else:
            return TokenizationAllowlistActivationParams(
                source = None,
                activation = True,
        )
        """

    def testTokenizationAllowlistActivationParams(self):
        """Test TokenizationAllowlistActivationParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
