# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    The version of the OpenAPI document: 1.1.0
    Contact: support@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.transaction_replacement import TransactionReplacement


class TestTransactionReplacement(unittest.TestCase):
    """TransactionReplacement unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TransactionReplacement:
        """Test TransactionReplacement
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TransactionReplacement`
        """
        model = TransactionReplacement()
        if include_optional:
            return TransactionReplacement(
                replaced_by_type = 'Resend',
                replaced_by_transaction_id = 'aff0e1cb-15b2-4e1f-9b9d-a9133715986f',
                replaced_by_transaction_hash = '239861be9a4afe080c359b7fe4a1d035945ec46256b1a0f44d1267c71de8ec28',
                replaced_type = 'Resend',
                replaced_transaction_id = 'aff0e1cb-15b2-4e1f-9b9d-a9133715986f',
                replaced_transaction_hash = '239861be9a4afe080c359b7fe4a1d035945ec46256b1a0f44d1267c71de8ec28'
            )
        else:
            return TransactionReplacement(
        )
        """

    def testTransactionReplacement(self):
        """Test TransactionReplacement"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
