# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: support@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.created_wallet_info import CreatedWalletInfo


class TestCreatedWalletInfo(unittest.TestCase):
    """CreatedWalletInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreatedWalletInfo:
        """Test CreatedWalletInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreatedWalletInfo`
        """
        model = CreatedWalletInfo()
        if include_optional:
            return CreatedWalletInfo(
                wallet_id = 'f47ac10b-58cc-4372-a567-0e02b2c3d479',
                wallet_type = 'Custodial',
                wallet_subtype = 'Asset',
                name = 'Example Wallet',
                org_id = 'f47ac10b-58cc-4372-a567-0e02b2c3d479',
                project_id = '0111039d-27fb-49ba-b172-6e0aa80e37ec',
                project_name = 'Project name',
                vault_id = '',
                vault_name = 'Vault name',
                apikey = 'd8f062da-39f4-4a11-8b9d-12595854237f',
                exchange_id = 'binance',
                main_wallet_id = 'f47ac10b-58cc-4372-a567-0e02b2c3d479'
            )
        else:
            return CreatedWalletInfo(
                wallet_id = 'f47ac10b-58cc-4372-a567-0e02b2c3d479',
                wallet_type = 'Custodial',
                wallet_subtype = 'Asset',
                name = 'Example Wallet',
                org_id = 'f47ac10b-58cc-4372-a567-0e02b2c3d479',
                vault_id = '',
                apikey = 'd8f062da-39f4-4a11-8b9d-12595854237f',
                exchange_id = 'binance',
        )
        """

    def testCreatedWalletInfo(self):
        """Test CreatedWalletInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
