# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.order_link_business_info import OrderLinkBusinessInfo


class TestOrderLinkBusinessInfo(unittest.TestCase):
    """OrderLinkBusinessInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OrderLinkBusinessInfo:
        """Test OrderLinkBusinessInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OrderLinkBusinessInfo`
        """
        model = OrderLinkBusinessInfo()
        if include_optional:
            return OrderLinkBusinessInfo(
                merchant_id = '1001',
                merchant_order_code = 'M20240201001',
                psp_order_code = 'P20240201001',
                pricing_currency = 'USD',
                pricing_amount = '100.00',
                fee_amount = '2.00',
                payable_currencies = ["ETH_USDT","SOL_USDC","TRON_USDT"],
                payable_amounts = [{"token_id":"ETH_USDT","amount":"103.03"},{"token_id":"SOL_USDC","amount":"105.05"}],
                expired_in = 1800,
                amount_tolerance = '0.5',
                currency = 'USD',
                order_amount = '100.00',
                token_ids = ["ETH_USDT","SOL_USDC","TRON_USDT"],
                custom_exchange_rates = [{"token_id":"ETH_USDT","exchange_rate":"0.99"},{"token_id":"SOL_USDC","exchange_rate":"1.02"}],
                use_dedicated_address = False
            )
        else:
            return OrderLinkBusinessInfo(
                merchant_id = '1001',
                psp_order_code = 'P20240201001',
                fee_amount = '2.00',
        )
        """

    def testOrderLinkBusinessInfo(self):
        """Test OrderLinkBusinessInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
