# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.create_custodial_wallet_params import CreateCustodialWalletParams


class TestCreateCustodialWalletParams(unittest.TestCase):
    """CreateCustodialWalletParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateCustodialWalletParams:
        """Test CreateCustodialWalletParams
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateCustodialWalletParams`
        """
        model = CreateCustodialWalletParams()
        if include_optional:
            return CreateCustodialWalletParams(
                name = 'My WaaS 2.0 Wallet',
                wallet_type = 'Custodial',
                wallet_subtype = 'Asset'
            )
        else:
            return CreateCustodialWalletParams(
                name = 'My WaaS 2.0 Wallet',
                wallet_type = 'Custodial',
                wallet_subtype = 'Asset',
        )
        """

    def testCreateCustodialWalletParams(self):
        """Test CreateCustodialWalletParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
