# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.policy_action_content import PolicyActionContent


class TestPolicyActionContent(unittest.TestCase):
    """PolicyActionContent unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PolicyActionContent:
        """Test PolicyActionContent
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PolicyActionContent`
        """
        model = PolicyActionContent()
        if include_optional:
            return PolicyActionContent(
                type = 'PART_APPROVAL',
                roles = [
                    'admin'
                    ],
                user_ids = [
                    'f47ac10b-58cc-4372-a567-0e02b2c3d479'
                    ],
                threshold = 15
            )
        else:
            return PolicyActionContent(
                type = 'PART_APPROVAL',
        )
        """

    def testPolicyActionContent(self):
        """Test PolicyActionContent"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
