# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.address_verification import AddressVerification


class TestAddressVerification(unittest.TestCase):
    """AddressVerification unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AddressVerification:
        """Test AddressVerification
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AddressVerification`
        """
        model = AddressVerification()
        if include_optional:
            return AddressVerification(
                verification_id = 'fb377ea5-a97a-49b4-955d-23f8fdd5177a',
                address = '0x1234567890abcdef1234567890abcdef12345678',
                chain_id = 'ETH',
                status = 'VERIFIED',
                verification_method = 'SATOSHI_TEST',
                verified_at = 1732523887000
            )
        else:
            return AddressVerification(
                verification_id = 'fb377ea5-a97a-49b4-955d-23f8fdd5177a',
                address = '0x1234567890abcdef1234567890abcdef12345678',
                chain_id = 'ETH',
                status = 'VERIFIED',
                verification_method = 'SATOSHI_TEST',
        )
        """

    def testAddressVerification(self):
        """Test AddressVerification"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
