# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.tokens_event_data import TokensEventData


class TestTokensEventData(unittest.TestCase):
    """TokensEventData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TokensEventData:
        """Test TokensEventData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TokensEventData`
        """
        model = TokensEventData()
        if include_optional:
            return TokensEventData(
                data_type = 'Transaction',
                tokens = [
                    cobo_waas2.models.token_info.TokenInfo(
                        token_id = 'ETH_USDT', 
                        chain_id = 'ETH', 
                        asset_id = 'USDT', 
                        symbol = 'USDT', 
                        name = 'Tether USDT', 
                        decimal = 18, 
                        icon_url = 'https://d.cobo.com/public/logos/USDT.png', 
                        token_address = '0xdAC17F958D2ee523a2206206994597C13D831ec7', 
                        fee_token_id = 'ETH', 
                        can_deposit = True, 
                        can_withdraw = True, 
                        dust_threshold = '0.00000546', 
                        custodial_minimum_deposit_threshold = '0.0001', 
                        asset_model_type = 'Account', )
                    ]
            )
        else:
            return TokensEventData(
                data_type = 'Transaction',
                tokens = [
                    cobo_waas2.models.token_info.TokenInfo(
                        token_id = 'ETH_USDT', 
                        chain_id = 'ETH', 
                        asset_id = 'USDT', 
                        symbol = 'USDT', 
                        name = 'Tether USDT', 
                        decimal = 18, 
                        icon_url = 'https://d.cobo.com/public/logos/USDT.png', 
                        token_address = '0xdAC17F958D2ee523a2206206994597C13D831ec7', 
                        fee_token_id = 'ETH', 
                        can_deposit = True, 
                        can_withdraw = True, 
                        dust_threshold = '0.00000546', 
                        custodial_minimum_deposit_threshold = '0.0001', 
                        asset_model_type = 'Account', )
                    ],
        )
        """

    def testTokensEventData(self):
        """Test TokensEventData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
