# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.delete_address_book_by_id201_response import DeleteAddressBookById201Response


class TestDeleteAddressBookById201Response(unittest.TestCase):
    """DeleteAddressBookById201Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeleteAddressBookById201Response:
        """Test DeleteAddressBookById201Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeleteAddressBookById201Response`
        """
        model = DeleteAddressBookById201Response()
        if include_optional:
            return DeleteAddressBookById201Response(
                submitted = True
            )
        else:
            return DeleteAddressBookById201Response(
                submitted = True,
        )
        """

    def testDeleteAddressBookById201Response(self):
        """Test DeleteAddressBookById201Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
