# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.create_webhook_event_params import CreateWebhookEventParams


class TestCreateWebhookEventParams(unittest.TestCase):
    """CreateWebhookEventParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateWebhookEventParams:
        """Test CreateWebhookEventParams
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateWebhookEventParams`
        """
        model = CreateWebhookEventParams()
        if include_optional:
            return CreateWebhookEventParams(
                channel_id = '',
                type = 'wallets.transaction.created',
                data = { },
                uuid = '',
                wallet_scopes_info = { },
                transaction_hash = '',
                request_id = '',
                transaction_id = '',
                cobo_id = ''
            )
        else:
            return CreateWebhookEventParams(
                channel_id = '',
                type = 'wallets.transaction.created',
                data = { },
                uuid = '',
        )
        """

    def testCreateWebhookEventParams(self):
        """Test CreateWebhookEventParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
