# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.create_batch_payout_request import CreateBatchPayoutRequest


class TestCreateBatchPayoutRequest(unittest.TestCase):
    """CreateBatchPayoutRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateBatchPayoutRequest:
        """Test CreateBatchPayoutRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateBatchPayoutRequest`
        """
        model = CreateBatchPayoutRequest()
        if include_optional:
            return CreateBatchPayoutRequest(
                description = 'Monthly vendor payments - January 2024',
                token_id = 'ETH_USDT',
                payout_mode = 'Normal',
                unlimited_token_approval = True,
                source = cobo_waas2.models.payout_source.PayoutSource(
                    wallet_id = '123e4567-e89b-12d3-a456-426614174003', 
                    address = '0xabc123def456ghi789jkl012mno345pqr678stu901', ),
                destinations = [
                    cobo_waas2.models.payout_destination.PayoutDestination(
                        address = '0xabc123def456ghi789jkl012mno345pqr678stu901', 
                        amount = '1.500000', 
                        email = 'recipient@example.com', 
                        note = 'Invoice #INV-2024-001', 
                        loop_enabled = True, 
                        network_fee = null, )
                    ]
            )
        else:
            return CreateBatchPayoutRequest(
                description = 'Monthly vendor payments - January 2024',
                token_id = 'ETH_USDT',
                payout_mode = 'Normal',
                source = cobo_waas2.models.payout_source.PayoutSource(
                    wallet_id = '123e4567-e89b-12d3-a456-426614174003', 
                    address = '0xabc123def456ghi789jkl012mno345pqr678stu901', ),
                destinations = [
                    cobo_waas2.models.payout_destination.PayoutDestination(
                        address = '0xabc123def456ghi789jkl012mno345pqr678stu901', 
                        amount = '1.500000', 
                        email = 'recipient@example.com', 
                        note = 'Invoice #INV-2024-001', 
                        loop_enabled = True, 
                        network_fee = null, )
                    ],
        )
        """

    def testCreateBatchPayoutRequest(self):
        """Test CreateBatchPayoutRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
