# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.payment_fee_type import PaymentFeeType


class TestPaymentFeeType(unittest.TestCase):
    """PaymentFeeType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaymentFeeType(self):
        """Test PaymentFeeType"""
        # inst = PaymentFeeType()


if __name__ == '__main__':
    unittest.main()
