# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.tokenization_unpause_estimate_fee_params import TokenizationUnpauseEstimateFeeParams


class TestTokenizationUnpauseEstimateFeeParams(unittest.TestCase):
    """TokenizationUnpauseEstimateFeeParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TokenizationUnpauseEstimateFeeParams:
        """Test TokenizationUnpauseEstimateFeeParams
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TokenizationUnpauseEstimateFeeParams`
        """
        model = TokenizationUnpauseEstimateFeeParams()
        if include_optional:
            return TokenizationUnpauseEstimateFeeParams(
                source = None,
                operation_type = 'Issue',
                token_id = '8a4f9324-ef2a-43cf-9f0e-d7f99999d3e8'
            )
        else:
            return TokenizationUnpauseEstimateFeeParams(
                source = None,
                operation_type = 'Issue',
                token_id = '8a4f9324-ef2a-43cf-9f0e-d7f99999d3e8',
        )
        """

    def testTokenizationUnpauseEstimateFeeParams(self):
        """Test TokenizationUnpauseEstimateFeeParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
