# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.tss_callback_request_type import TSSCallbackRequestType


class TestTSSCallbackRequestType(unittest.TestCase):
    """TSSCallbackRequestType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTSSCallbackRequestType(self):
        """Test TSSCallbackRequestType"""
        # inst = TSSCallbackRequestType()


if __name__ == '__main__':
    unittest.main()
