# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.mpc_signing_group import MpcSigningGroup


class TestMpcSigningGroup(unittest.TestCase):
    """MpcSigningGroup unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MpcSigningGroup:
        """Test MpcSigningGroup
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MpcSigningGroup`
        """
        model = MpcSigningGroup()
        if include_optional:
            return MpcSigningGroup(
                used_key_share_holder_group_id = 'f47ac10b-58cc-4372-a567-0e02b2c3d479',
                used_tss_node_ids = [
                    'cobo5yb7BNEBwwp5XXedbhnzQfvQtp132W4dH4Jz4x4eDp4KA'
                    ]
            )
        else:
            return MpcSigningGroup(
                used_key_share_holder_group_id = 'f47ac10b-58cc-4372-a567-0e02b2c3d479',
        )
        """

    def testMpcSigningGroup(self):
        """Test MpcSigningGroup"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
