# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.babylon_registration_status import BabylonRegistrationStatus


class TestBabylonRegistrationStatus(unittest.TestCase):
    """BabylonRegistrationStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBabylonRegistrationStatus(self):
        """Test BabylonRegistrationStatus"""
        # inst = BabylonRegistrationStatus()


if __name__ == '__main__':
    unittest.main()
