# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.payment_developer_subscription_action_data import PaymentDeveloperSubscriptionActionData


class TestPaymentDeveloperSubscriptionActionData(unittest.TestCase):
    """PaymentDeveloperSubscriptionActionData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentDeveloperSubscriptionActionData:
        """Test PaymentDeveloperSubscriptionActionData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentDeveloperSubscriptionActionData`
        """
        model = PaymentDeveloperSubscriptionActionData()
        if include_optional:
            return PaymentDeveloperSubscriptionActionData(
                action_type = cobo_waas2.models.payment_subscription_action.PaymentSubscriptionAction(
                    request_id = '123e457-e89b-12d3-a456-426614174004', 
                    subscription_action_id = '123e457-e89b-12d3-a456-426614174004', 
                    plan_id = '123e457-e89b-12d3-a456-426614174004', 
                    subscription_id = '123e457-e89b-12d3-a456-426614174004', 
                    merchant_id = '123e457-e89b-12d3-a456-426614174004', 
                    merchant_address = '0x8a73abedb3053b17204b887af6231a8ac35fc2cc', 
                    data = null, 
                    status = 'Pending', 
                    created_timestamp = 1744689600, 
                    updated_timestamp = 1744689600, ),
                subscription_id = '123e457-e89b-12d3-a456-426614174004'
            )
        else:
            return PaymentDeveloperSubscriptionActionData(
                action_type = cobo_waas2.models.payment_subscription_action.PaymentSubscriptionAction(
                    request_id = '123e457-e89b-12d3-a456-426614174004', 
                    subscription_action_id = '123e457-e89b-12d3-a456-426614174004', 
                    plan_id = '123e457-e89b-12d3-a456-426614174004', 
                    subscription_id = '123e457-e89b-12d3-a456-426614174004', 
                    merchant_id = '123e457-e89b-12d3-a456-426614174004', 
                    merchant_address = '0x8a73abedb3053b17204b887af6231a8ac35fc2cc', 
                    data = null, 
                    status = 'Pending', 
                    created_timestamp = 1744689600, 
                    updated_timestamp = 1744689600, ),
                subscription_id = '123e457-e89b-12d3-a456-426614174004',
        )
        """

    def testPaymentDeveloperSubscriptionActionData(self):
        """Test PaymentDeveloperSubscriptionActionData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
