# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.payout_destination_detail import PayoutDestinationDetail


class TestPayoutDestinationDetail(unittest.TestCase):
    """PayoutDestinationDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PayoutDestinationDetail:
        """Test PayoutDestinationDetail
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PayoutDestinationDetail`
        """
        model = PayoutDestinationDetail()
        if include_optional:
            return PayoutDestinationDetail(
                address = '0xabc123def456ghi789jkl012mno345pqr678stu901',
                amount = '1.500000',
                email = 'recipient@example.com',
                note = 'Invoice #INV-2024-001',
                loop_enabled = True,
                network_fee = None,
                status = 'Submitted',
                transaction_id = '123e4567-e89b-12d3-a456-426614174003'
            )
        else:
            return PayoutDestinationDetail(
                address = '0xabc123def456ghi789jkl012mno345pqr678stu901',
                amount = '1.500000',
        )
        """

    def testPayoutDestinationDetail(self):
        """Test PayoutDestinationDetail"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
