# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.transaction_core_stake_info import TransactionCoreStakeInfo


class TestTransactionCoreStakeInfo(unittest.TestCase):
    """TransactionCoreStakeInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TransactionCoreStakeInfo:
        """Test TransactionCoreStakeInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TransactionCoreStakeInfo`
        """
        model = TransactionCoreStakeInfo()
        if include_optional:
            return TransactionCoreStakeInfo(
                extra_type = 'BabylonBusinessInfo',
                stake_amount = '100.00',
                timelock = 56,
                change_address = '',
                validator_address = '',
                reward_address = ''
            )
        else:
            return TransactionCoreStakeInfo(
                extra_type = 'BabylonBusinessInfo',
        )
        """

    def testTransactionCoreStakeInfo(self):
        """Test TransactionCoreStakeInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
