# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.payment_uploaded_file import PaymentUploadedFile


class TestPaymentUploadedFile(unittest.TestCase):
    """PaymentUploadedFile unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PaymentUploadedFile:
        """Test PaymentUploadedFile
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PaymentUploadedFile`
        """
        model = PaymentUploadedFile()
        if include_optional:
            return PaymentUploadedFile(
                file_id = 'https://example-bucket.s3.us-east-1.amazonaws.com/uploads/business_registration.pdf',
                expired_timestamp = 1701483266000
            )
        else:
            return PaymentUploadedFile(
                file_id = 'https://example-bucket.s3.us-east-1.amazonaws.com/uploads/business_registration.pdf',
                expired_timestamp = 1701483266000,
        )
        """

    def testPaymentUploadedFile(self):
        """Test PaymentUploadedFile"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
