# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.disposition_response import DispositionResponse


class TestDispositionResponse(unittest.TestCase):
    """DispositionResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DispositionResponse:
        """Test DispositionResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DispositionResponse`
        """
        model = DispositionResponse()
        if include_optional:
            return DispositionResponse(
                transaction_id = 'f47ac10b-58cc-4372-a567-0e02b2c3d479',
                status = 'Submitted'
            )
        else:
            return DispositionResponse(
                transaction_id = 'f47ac10b-58cc-4372-a567-0e02b2c3d479',
                status = 'Submitted',
        )
        """

    def testDispositionResponse(self):
        """Test DispositionResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
