# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.stellar_contract_call_trust_line_param import StellarContractCallTrustLineParam


class TestStellarContractCallTrustLineParam(unittest.TestCase):
    """StellarContractCallTrustLineParam unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> StellarContractCallTrustLineParam:
        """Test StellarContractCallTrustLineParam
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `StellarContractCallTrustLineParam`
        """
        model = StellarContractCallTrustLineParam()
        if include_optional:
            return StellarContractCallTrustLineParam(
                contract_type = 'TrustLine',
                token_id = 'XLM_USDC',
                operation_type = 'ChangeTrust'
            )
        else:
            return StellarContractCallTrustLineParam(
                contract_type = 'TrustLine',
                token_id = 'XLM_USDC',
                operation_type = 'ChangeTrust',
        )
        """

    def testStellarContractCallTrustLineParam(self):
        """Test StellarContractCallTrustLineParam"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
