# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.broadcast_signed_transactions_request import BroadcastSignedTransactionsRequest


class TestBroadcastSignedTransactionsRequest(unittest.TestCase):
    """BroadcastSignedTransactionsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BroadcastSignedTransactionsRequest:
        """Test BroadcastSignedTransactionsRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BroadcastSignedTransactionsRequest`
        """
        model = BroadcastSignedTransactionsRequest()
        if include_optional:
            return BroadcastSignedTransactionsRequest(
                transaction_ids = [
                    'f47ac10b-58cc-4372-a567-0e02b2c3d479'
                    ]
            )
        else:
            return BroadcastSignedTransactionsRequest(
        )
        """

    def testBroadcastSignedTransactionsRequest(self):
        """Test BroadcastSignedTransactionsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
