# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.kya_screening_status import KyaScreeningStatus


class TestKyaScreeningStatus(unittest.TestCase):
    """KyaScreeningStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testKyaScreeningStatus(self):
        """Test KyaScreeningStatus"""
        # inst = KyaScreeningStatus()


if __name__ == '__main__':
    unittest.main()
