# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: support@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.list_exchanges200_response_inner import ListExchanges200ResponseInner


class TestListExchanges200ResponseInner(unittest.TestCase):
    """ListExchanges200ResponseInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListExchanges200ResponseInner:
        """Test ListExchanges200ResponseInner
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListExchanges200ResponseInner`
        """
        model = ListExchanges200ResponseInner()
        if include_optional:
            return ListExchanges200ResponseInner(
                exchange_id = 'binance',
                supported_trading_account_types = ["Spot","Asset"]
            )
        else:
            return ListExchanges200ResponseInner(
                exchange_id = 'binance',
                supported_trading_account_types = ["Spot","Asset"],
        )
        """

    def testListExchanges200ResponseInner(self):
        """Test ListExchanges200ResponseInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
