# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.update_key_share_holder_group_by_id_request import UpdateKeyShareHolderGroupByIdRequest


class TestUpdateKeyShareHolderGroupByIdRequest(unittest.TestCase):
    """UpdateKeyShareHolderGroupByIdRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateKeyShareHolderGroupByIdRequest:
        """Test UpdateKeyShareHolderGroupByIdRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateKeyShareHolderGroupByIdRequest`
        """
        model = UpdateKeyShareHolderGroupByIdRequest()
        if include_optional:
            return UpdateKeyShareHolderGroupByIdRequest(
                update_key_share_holder_group_action = 'UpgradeToMainGroup'
            )
        else:
            return UpdateKeyShareHolderGroupByIdRequest(
                update_key_share_holder_group_action = 'UpgradeToMainGroup',
        )
        """

    def testUpdateKeyShareHolderGroupByIdRequest(self):
        """Test UpdateKeyShareHolderGroupByIdRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
