# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.tokenization_activity_status import TokenizationActivityStatus


class TestTokenizationActivityStatus(unittest.TestCase):
    """TokenizationActivityStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTokenizationActivityStatus(self):
        """Test TokenizationActivityStatus"""
        # inst = TokenizationActivityStatus()


if __name__ == '__main__':
    unittest.main()
