# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.tss_key_share_sign_request import TSSKeyShareSignRequest


class TestTSSKeyShareSignRequest(unittest.TestCase):
    """TSSKeyShareSignRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TSSKeyShareSignRequest:
        """Test TSSKeyShareSignRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TSSKeyShareSignRequest`
        """
        model = TSSKeyShareSignRequest()
        if include_optional:
            return TSSKeyShareSignRequest(
                node_id = 'coboAbCdEfGhIjKlMnOpQrStUvWxYz1234567890abcdefghi',
                task_id = '20231213122855000000000000000000',
                details = [
                    cobo_waas2.models.tss_key_share_sign_detail.TSSKeyShareSignDetail(
                        group_id = 'mMedDioOKhTlhGyQRzMv', 
                        message = '', )
                    ],
                biz_task_id = 'aff0e1cb-15b2-4e1f-9b9d-a9133715986f'
            )
        else:
            return TSSKeyShareSignRequest(
        )
        """

    def testTSSKeyShareSignRequest(self):
        """Test TSSKeyShareSignRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
