# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.tokenization_token_standard import TokenizationTokenStandard


class TestTokenizationTokenStandard(unittest.TestCase):
    """TokenizationTokenStandard unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTokenizationTokenStandard(self):
        """Test TokenizationTokenStandard"""
        # inst = TokenizationTokenStandard()


if __name__ == '__main__':
    unittest.main()
