# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.tss_participant import TSSParticipant


class TestTSSParticipant(unittest.TestCase):
    """TSSParticipant unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TSSParticipant:
        """Test TSSParticipant
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TSSParticipant`
        """
        model = TSSParticipant()
        if include_optional:
            return TSSParticipant(
                node_id = 'coboAbCdEfGhIjKlMnOpQrStUvWxYz1234567890abcdefghi',
                share_id = '619693302942100684578205955442284626185',
                share_public_key = '0x217223cdea6b19af34131447763a269d1dbef580bc85272a5bdfc59fa4940cca'
            )
        else:
            return TSSParticipant(
        )
        """

    def testTSSParticipant(self):
        """Test TSSParticipant"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
