# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.merchant_kyc_company_attachment_file_type import MerchantKycCompanyAttachmentFileType


class TestMerchantKycCompanyAttachmentFileType(unittest.TestCase):
    """MerchantKycCompanyAttachmentFileType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMerchantKycCompanyAttachmentFileType(self):
        """Test MerchantKycCompanyAttachmentFileType"""
        # inst = MerchantKycCompanyAttachmentFileType()


if __name__ == '__main__':
    unittest.main()
