# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.satoshi_test_challenge_action import SatoshiTestChallengeAction


class TestSatoshiTestChallengeAction(unittest.TestCase):
    """SatoshiTestChallengeAction unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSatoshiTestChallengeAction(self):
        """Test SatoshiTestChallengeAction"""
        # inst = SatoshiTestChallengeAction()


if __name__ == '__main__':
    unittest.main()
