# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.approval_template import ApprovalTemplate


class TestApprovalTemplate(unittest.TestCase):
    """ApprovalTemplate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ApprovalTemplate:
        """Test ApprovalTemplate
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ApprovalTemplate`
        """
        model = ApprovalTemplate()
        if include_optional:
            return ApprovalTemplate(
                business_key = 'transaction_withdrawal',
                template_text = '{{user_name}} requests to withdraw {{amount}} {{currency}} from the account.',
                template_version = '1.0.0'
            )
        else:
            return ApprovalTemplate(
        )
        """

    def testApprovalTemplate(self):
        """Test ApprovalTemplate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
