# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.balance_at_block import BalanceAtBlock


class TestBalanceAtBlock(unittest.TestCase):
    """BalanceAtBlock unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BalanceAtBlock:
        """Test BalanceAtBlock
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BalanceAtBlock`
        """
        model = BalanceAtBlock()
        if include_optional:
            return BalanceAtBlock(
                address = '0x1c53e3f2f8b59e5d6b6b6b6b6b6b6b6b6b6b6b6b',
                token_id = 'ETH_USDT',
                balance = '1000.5',
                block_number = 20000000
            )
        else:
            return BalanceAtBlock(
        )
        """

    def testBalanceAtBlock(self):
        """Test BalanceAtBlock"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
