# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.tokenization_issue_token_params import TokenizationIssueTokenParams


class TestTokenizationIssueTokenParams(unittest.TestCase):
    """TokenizationIssueTokenParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TokenizationIssueTokenParams:
        """Test TokenizationIssueTokenParams
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TokenizationIssueTokenParams`
        """
        model = TokenizationIssueTokenParams()
        if include_optional:
            return TokenizationIssueTokenParams(
                chain_id = 'ETH',
                source = None,
                token_params = None
            )
        else:
            return TokenizationIssueTokenParams(
                chain_id = 'ETH',
                source = None,
                token_params = None,
        )
        """

    def testTokenizationIssueTokenParams(self):
        """Test TokenizationIssueTokenParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
