# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.satoshi_test_challenge import SatoshiTestChallenge


class TestSatoshiTestChallenge(unittest.TestCase):
    """SatoshiTestChallenge unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SatoshiTestChallenge:
        """Test SatoshiTestChallenge
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SatoshiTestChallenge`
        """
        model = SatoshiTestChallenge()
        if include_optional:
            return SatoshiTestChallenge(
                challenge_id = 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
                from_address = '0x1234567890abcdef1234567890abcdef12345678',
                to_address = '0xabcdef1234567890abcdef1234567890abcdef12',
                amount = '1100001000000000',
                token_id = 'ETH',
                chain_id = 'ETH',
                status = 'PENDING',
                remaining_seconds = 10550,
                matched_txid = '0xabc123...',
                started_at = 1732523887000,
                expires_at = 1732534687000
            )
        else:
            return SatoshiTestChallenge(
                challenge_id = 'a1b2c3d4-e5f6-7890-abcd-ef1234567890',
                from_address = '0x1234567890abcdef1234567890abcdef12345678',
                to_address = '0xabcdef1234567890abcdef1234567890abcdef12',
                amount = '1100001000000000',
                token_id = 'ETH',
                chain_id = 'ETH',
                status = 'PENDING',
                remaining_seconds = 10550,
        )
        """

    def testSatoshiTestChallenge(self):
        """Test SatoshiTestChallenge"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
