# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.tss_key_gen_request import TSSKeyGenRequest


class TestTSSKeyGenRequest(unittest.TestCase):
    """TSSKeyGenRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TSSKeyGenRequest:
        """Test TSSKeyGenRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TSSKeyGenRequest`
        """
        model = TSSKeyGenRequest()
        if include_optional:
            return TSSKeyGenRequest(
                threshold = 2,
                node_ids = [
                    '["coboAbCdEfGhIjKlMnOpQrStUvWxYz1234567890abcdefghi","coboBTGDvjJG99pABegvPYmavrcTU3SkjTLHVdsko8dWBga4w"]'
                    ],
                curve = 0,
                task_id = '20231213122855000000000000000000',
                biz_task_id = '20231213122855000000000000000000'
            )
        else:
            return TSSKeyGenRequest(
        )
        """

    def testTSSKeyGenRequest(self):
        """Test TSSKeyGenRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
