# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.tokenization_sol_wrapped_token_params import TokenizationSOLWrappedTokenParams


class TestTokenizationSOLWrappedTokenParams(unittest.TestCase):
    """TokenizationSOLWrappedTokenParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TokenizationSOLWrappedTokenParams:
        """Test TokenizationSOLWrappedTokenParams
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TokenizationSOLWrappedTokenParams`
        """
        model = TokenizationSOLWrappedTokenParams()
        if include_optional:
            return TokenizationSOLWrappedTokenParams(
                standard = 'ERC20',
                name = 'My Awesome Token',
                symbol = 'MAT',
                underlying_token = '9WzDXwBbmkg8ZTbNMqUxvQRAyrZzDsGYdLVL9zYtAWWM',
                token_access_activated = False,
                permissions = cobo_waas2.models.tokenization_sol_wrapped_token_permission_params.TokenizationSolWrappedTokenPermissionParams(
                    wrapper = ["9WzDXwBbmkg8ZTbNMqUxvQRAyrZzDsGYdLVL9zYtAWWM","7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU"], 
                    pauser = '9WzDXwBbmkg8ZTbNMqUxvQRAyrZzDsGYdLVL9zYtAWWM', 
                    freezer = '9WzDXwBbmkg8ZTbNMqUxvQRAyrZzDsGYdLVL9zYtAWWM', 
                    updater = '9WzDXwBbmkg8ZTbNMqUxvQRAyrZzDsGYdLVL9zYtAWWM', )
            )
        else:
            return TokenizationSOLWrappedTokenParams(
                standard = 'ERC20',
                name = 'My Awesome Token',
                symbol = 'MAT',
                underlying_token = '9WzDXwBbmkg8ZTbNMqUxvQRAyrZzDsGYdLVL9zYtAWWM',
        )
        """

    def testTokenizationSOLWrappedTokenParams(self):
        """Test TokenizationSOLWrappedTokenParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
