# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.merchant_balance import MerchantBalance


class TestMerchantBalance(unittest.TestCase):
    """MerchantBalance unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MerchantBalance:
        """Test MerchantBalance
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MerchantBalance`
        """
        model = MerchantBalance()
        if include_optional:
            return MerchantBalance(
                merchant_id = '1',
                token_id = 'ETH_USDT',
                acquiring_type = 'Order',
                total_received_amount = '1.23',
                settled_amount = '1.23',
                refunded_amount = '1.23',
                total_balance = '1.23',
                available_balance = '1.23',
                locked_balance = '1.23'
            )
        else:
            return MerchantBalance(
                merchant_id = '1',
                token_id = 'ETH_USDT',
                acquiring_type = 'Order',
        )
        """

    def testMerchantBalance(self):
        """Test MerchantBalance"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
