# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.settlement_info import SettlementInfo


class TestSettlementInfo(unittest.TestCase):
    """SettlementInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SettlementInfo:
        """Test SettlementInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SettlementInfo`
        """
        model = SettlementInfo()
        if include_optional:
            return SettlementInfo(
                merchant_id = '123',
                token_id = 'ETH_USDT',
                available_amount = '500.00',
                available_currency_balance = '500.00',
                pending_amount = '500.00',
                pending_currency_balance = '500.00'
            )
        else:
            return SettlementInfo(
                available_amount = '500.00',
        )
        """

    def testSettlementInfo(self):
        """Test SettlementInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
