# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.create_token_listing_request201_response import CreateTokenListingRequest201Response


class TestCreateTokenListingRequest201Response(unittest.TestCase):
    """CreateTokenListingRequest201Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateTokenListingRequest201Response:
        """Test CreateTokenListingRequest201Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateTokenListingRequest201Response`
        """
        model = CreateTokenListingRequest201Response()
        if include_optional:
            return CreateTokenListingRequest201Response(
                request_id = '123e4567e89b12d3a456426614174000'
            )
        else:
            return CreateTokenListingRequest201Response(
                request_id = '123e4567e89b12d3a456426614174000',
        )
        """

    def testCreateTokenListingRequest201Response(self):
        """Test CreateTokenListingRequest201Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
