# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    The version of the OpenAPI document: 1.1.0
    Contact: support@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.tss_request_type import TSSRequestType


class TestTSSRequestType(unittest.TestCase):
    """TSSRequestType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTSSRequestType(self):
        """Test TSSRequestType"""
        # inst = TSSRequestType()


if __name__ == '__main__':
    unittest.main()
