# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.get_reports200_response import GetReports200Response


class TestGetReports200Response(unittest.TestCase):
    """GetReports200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetReports200Response:
        """Test GetReports200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetReports200Response`
        """
        model = GetReports200Response()
        if include_optional:
            return GetReports200Response(
                data = [
                    cobo_waas2.models.report.Report(
                        report_id = '123e4567-e89b-12d3-a456-426614174004', 
                        report_types = [
                            'OrderIn'
                            ], 
                        start_time = 1764237462, 
                        end_time = 1764237462, 
                        created_timestamp = 1744689600, 
                        report_url = 'https://cobo.com/reports/123e4567-e89b-12d3-a456-426614174004', 
                        report_export_format = 'CSV', 
                        report_status = 'Completed', 
                        initiator = 'b2ae1b5aaade686c968ef2bbd31cc75ba94e5a85fd9cb0b85b81dcc15f920e9d', )
                    ],
                pagination = cobo_waas2.models.pagination.Pagination(
                    before = 'RqeEoTkgKG5rpzqYzg2Hd3szmPoj2cE7w5jWwShz3C1vyGmk1', 
                    after = 'RqeEoTkgKG5rpzqYzg2Hd3szmPoj2cE7w5jWwShz3C1vyGSAk', 
                    total_count = 10000, )
            )
        else:
            return GetReports200Response(
        )
        """

    def testGetReports200Response(self):
        """Test GetReports200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
