# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    The version of the OpenAPI document: 1.1.0
    Contact: support@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.update_smart_contract_wallet_params import UpdateSmartContractWalletParams


class TestUpdateSmartContractWalletParams(unittest.TestCase):
    """UpdateSmartContractWalletParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateSmartContractWalletParams:
        """Test UpdateSmartContractWalletParams
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateSmartContractWalletParams`
        """
        model = UpdateSmartContractWalletParams()
        if include_optional:
            return UpdateSmartContractWalletParams(
                wallet_type = 'Custodial',
                name = 'My WaaS 2.0 Wallet'
            )
        else:
            return UpdateSmartContractWalletParams(
                wallet_type = 'Custodial',
        )
        """

    def testUpdateSmartContractWalletParams(self):
        """Test UpdateSmartContractWalletParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
