# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.balance_update_info import BalanceUpdateInfo


class TestBalanceUpdateInfo(unittest.TestCase):
    """BalanceUpdateInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BalanceUpdateInfo:
        """Test BalanceUpdateInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BalanceUpdateInfo`
        """
        model = BalanceUpdateInfo()
        if include_optional:
            return BalanceUpdateInfo(
                token_id = 'BTC',
                address = '0x0000000000000000000000000000000000000000',
                wallet_uuid = 'f47ac10b-58cc-4372-a567-0e02b2c3d479',
                updated_timestamp = 1640995200000,
                balance = cobo_waas2.models.balance.Balance(
                    total = '100.0', 
                    available = '80.5', 
                    pending = '0', 
                    locked = '0', 
                    frozen = '0', )
            )
        else:
            return BalanceUpdateInfo(
                token_id = 'BTC',
                address = '0x0000000000000000000000000000000000000000',
                wallet_uuid = 'f47ac10b-58cc-4372-a567-0e02b2c3d479',
                updated_timestamp = 1640995200000,
                balance = cobo_waas2.models.balance.Balance(
                    total = '100.0', 
                    available = '80.5', 
                    pending = '0', 
                    locked = '0', 
                    frozen = '0', ),
        )
        """

    def testBalanceUpdateInfo(self):
        """Test BalanceUpdateInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
