# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.compliance_kya_screenings_update_event_data import ComplianceKyaScreeningsUpdateEventData


class TestComplianceKyaScreeningsUpdateEventData(unittest.TestCase):
    """ComplianceKyaScreeningsUpdateEventData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ComplianceKyaScreeningsUpdateEventData:
        """Test ComplianceKyaScreeningsUpdateEventData
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ComplianceKyaScreeningsUpdateEventData`
        """
        model = ComplianceKyaScreeningsUpdateEventData()
        if include_optional:
            return ComplianceKyaScreeningsUpdateEventData(
                data_type = 'Transaction',
                screening_id = 'a7b8c9d0-e1f2-4a5b-a23c-7890abcdef12',
                address = '0x1234567890abcdef1234567890abcdef12345678',
                chain_id = 'ETH',
                status = 'Screened',
                created_timestamp = 1721530814236,
                updated_timestamp = 1721530899876
            )
        else:
            return ComplianceKyaScreeningsUpdateEventData(
                data_type = 'Transaction',
                screening_id = 'a7b8c9d0-e1f2-4a5b-a23c-7890abcdef12',
                address = '0x1234567890abcdef1234567890abcdef12345678',
                chain_id = 'ETH',
                status = 'Screened',
                created_timestamp = 1721530814236,
                updated_timestamp = 1721530899876,
        )
        """

    def testComplianceKyaScreeningsUpdateEventData(self):
        """Test ComplianceKyaScreeningsUpdateEventData"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
