# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.auto_sweep_task import AutoSweepTask


class TestAutoSweepTask(unittest.TestCase):
    """AutoSweepTask unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AutoSweepTask:
        """Test AutoSweepTask
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AutoSweepTask`
        """
        model = AutoSweepTask()
        if include_optional:
            return AutoSweepTask(
                task_id = 'aff0e1cb-15b2-4e1f-9b9d-a9133715986f',
                wallet_id = 'f47ac10b-58cc-4372-a567-0e02b2c3d479',
                token_id = 'ETH_USDT',
                status = 'Submitted',
                transaction_ids = [
                    '0011039d-27fb-49ba-b172-6e0aa80e37ec'
                    ],
                failed_reasons = [
                    'exist pending transaction'
                    ],
                created_timestamp = 1610445878970,
                updated_timestamp = 1610445878970
            )
        else:
            return AutoSweepTask(
                task_id = 'aff0e1cb-15b2-4e1f-9b9d-a9133715986f',
                wallet_id = 'f47ac10b-58cc-4372-a567-0e02b2c3d479',
                token_id = 'ETH_USDT',
                status = 'Submitted',
                created_timestamp = 1610445878970,
        )
        """

    def testAutoSweepTask(self):
        """Test AutoSweepTask"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
