# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.destination_bank_account_tag import DestinationBankAccountTag


class TestDestinationBankAccountTag(unittest.TestCase):
    """DestinationBankAccountTag unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDestinationBankAccountTag(self):
        """Test DestinationBankAccountTag"""
        # inst = DestinationBankAccountTag()


if __name__ == '__main__':
    unittest.main()
