# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.tokenization_sol_wrapped_token_permission_params import TokenizationSolWrappedTokenPermissionParams


class TestTokenizationSolWrappedTokenPermissionParams(unittest.TestCase):
    """TokenizationSolWrappedTokenPermissionParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TokenizationSolWrappedTokenPermissionParams:
        """Test TokenizationSolWrappedTokenPermissionParams
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TokenizationSolWrappedTokenPermissionParams`
        """
        model = TokenizationSolWrappedTokenPermissionParams()
        if include_optional:
            return TokenizationSolWrappedTokenPermissionParams(
                wrapper = ["9WzDXwBbmkg8ZTbNMqUxvQRAyrZzDsGYdLVL9zYtAWWM","7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU"],
                pauser = ["9WzDXwBbmkg8ZTbNMqUxvQRAyrZzDsGYdLVL9zYtAWWM"]
            )
        else:
            return TokenizationSolWrappedTokenPermissionParams(
        )
        """

    def testTokenizationSolWrappedTokenPermissionParams(self):
        """Test TokenizationSolWrappedTokenPermissionParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
