# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.max_transferable_value import MaxTransferableValue


class TestMaxTransferableValue(unittest.TestCase):
    """MaxTransferableValue unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MaxTransferableValue:
        """Test MaxTransferableValue
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MaxTransferableValue`
        """
        model = MaxTransferableValue()
        if include_optional:
            return MaxTransferableValue(
                token_id = 'ETH',
                max_transferable_value = '3.0',
                fee = None
            )
        else:
            return MaxTransferableValue(
        )
        """

    def testMaxTransferableValue(self):
        """Test MaxTransferableValue"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
