# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.transaction_cosmos_adr36_destination import TransactionCosmosAdr36Destination


class TestTransactionCosmosAdr36Destination(unittest.TestCase):
    """TransactionCosmosAdr36Destination unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TransactionCosmosAdr36Destination:
        """Test TransactionCosmosAdr36Destination
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TransactionCosmosAdr36Destination`
        """
        model = TransactionCosmosAdr36Destination()
        if include_optional:
            return TransactionCosmosAdr36Destination(
                destination_type = 'Address',
                message_cosmos_adr36 = ''
            )
        else:
            return TransactionCosmosAdr36Destination(
                destination_type = 'Address',
                message_cosmos_adr36 = '',
        )
        """

    def testTransactionCosmosAdr36Destination(self):
        """Test TransactionCosmosAdr36Destination"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
