# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.fil_price import FILPrice


class TestFILPrice(unittest.TestCase):
    """FILPrice unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FILPrice:
        """Test FILPrice
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FILPrice`
        """
        model = FILPrice()
        if include_optional:
            return FILPrice(
                gas_premium = '0.0001',
                gas_fee_cap = '0.00035',
                gas_limit = '500'
            )
        else:
            return FILPrice(
        )
        """

    def testFILPrice(self):
        """Test FILPrice"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
