# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.create_sweep_to_address import CreateSweepToAddress


class TestCreateSweepToAddress(unittest.TestCase):
    """CreateSweepToAddress unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateSweepToAddress:
        """Test CreateSweepToAddress
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateSweepToAddress`
        """
        model = CreateSweepToAddress()
        if include_optional:
            return CreateSweepToAddress(
                wallet_id = 'f47ac10b-58cc-4372-a567-0e02b2c3d479',
                chain_id = 'ETH'
            )
        else:
            return CreateSweepToAddress(
                wallet_id = 'f47ac10b-58cc-4372-a567-0e02b2c3d479',
                chain_id = 'ETH',
        )
        """

    def testCreateSweepToAddress(self):
        """Test CreateSweepToAddress"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
