# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    The version of the OpenAPI document: 1.0.0
    Contact: support@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.evm_eip1559_fee_base_price import EvmEip1559FeeBasePrice


class TestEvmEip1559FeeBasePrice(unittest.TestCase):
    """EvmEip1559FeeBasePrice unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> EvmEip1559FeeBasePrice:
        """Test EvmEip1559FeeBasePrice
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `EvmEip1559FeeBasePrice`
        """
        model = EvmEip1559FeeBasePrice()
        if include_optional:
            return EvmEip1559FeeBasePrice(
                max_fee_per_gas = '9000000000000',
                max_priority_fee_per_gas = '1000000000000'
            )
        else:
            return EvmEip1559FeeBasePrice(
        )
        """

    def testEvmEip1559FeeBasePrice(self):
        """Test EvmEip1559FeeBasePrice"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
