# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.babylon_staking_activity_detail_extra import BabylonStakingActivityDetailExtra


class TestBabylonStakingActivityDetailExtra(unittest.TestCase):
    """BabylonStakingActivityDetailExtra unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> BabylonStakingActivityDetailExtra:
        """Test BabylonStakingActivityDetailExtra
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BabylonStakingActivityDetailExtra`
        """
        model = BabylonStakingActivityDetailExtra()
        if include_optional:
            return BabylonStakingActivityDetailExtra(
                pool_type = 'Babylon',
                finality_provider_public_key = 'eca1b104dce16c30705f4147a9c4a373ac88646c5d1bcda6a89c018940cb96a0',
                stake_block_time = 2000,
                auto_broadcast = False,
                param_version = 2,
                withdraw_from_type = 'Stake'
            )
        else:
            return BabylonStakingActivityDetailExtra(
                pool_type = 'Babylon',
        )
        """

    def testBabylonStakingActivityDetailExtra(self):
        """Test BabylonStakingActivityDetailExtra"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
