# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.list_token_balances_for_fee_station200_response import ListTokenBalancesForFeeStation200Response


class TestListTokenBalancesForFeeStation200Response(unittest.TestCase):
    """ListTokenBalancesForFeeStation200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListTokenBalancesForFeeStation200Response:
        """Test ListTokenBalancesForFeeStation200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListTokenBalancesForFeeStation200Response`
        """
        model = ListTokenBalancesForFeeStation200Response()
        if include_optional:
            return ListTokenBalancesForFeeStation200Response(
                data = [
                    cobo_waas2.models.list_token_balances_for_fee_station_200_response_data_inner.list_token_balances_for_fee_station_200_response_data_inner(
                        token_id = 'ETH', 
                        chain_id = 'ETH', 
                        balance = cobo_waas2.models.balance.Balance(
                            total = '100.0', 
                            available = '80.5', 
                            pending = '0', 
                            locked = '0', 
                            frozen = '0', ), )
                    ],
                pagination = cobo_waas2.models.pagination.Pagination(
                    before = 'RqeEoTkgKG5rpzqYzg2Hd3szmPoj2cE7w5jWwShz3C1vyGmk1', 
                    after = 'RqeEoTkgKG5rpzqYzg2Hd3szmPoj2cE7w5jWwShz3C1vyGSAk', 
                    total_count = 10000, )
            )
        else:
            return ListTokenBalancesForFeeStation200Response(
        )
        """

    def testListTokenBalancesForFeeStation200Response(self):
        """Test ListTokenBalancesForFeeStation200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
