# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.merchant_kyc_person_attachment import MerchantKycPersonAttachment


class TestMerchantKycPersonAttachment(unittest.TestCase):
    """MerchantKycPersonAttachment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MerchantKycPersonAttachment:
        """Test MerchantKycPersonAttachment
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MerchantKycPersonAttachment`
        """
        model = MerchantKycPersonAttachment()
        if include_optional:
            return MerchantKycPersonAttachment(
                file_id = 'https://example-bucket.s3.us-east-1.amazonaws.com/uploads/id_card_front.jpg',
                file_type = 'PRC_ID_Emblem'
            )
        else:
            return MerchantKycPersonAttachment(
                file_id = 'https://example-bucket.s3.us-east-1.amazonaws.com/uploads/id_card_front.jpg',
                file_type = 'PRC_ID_Emblem',
        )
        """

    def testMerchantKycPersonAttachment(self):
        """Test MerchantKycPersonAttachment"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
