# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.query_destination_whitelist_enabled200_response import QueryDestinationWhitelistEnabled200Response


class TestQueryDestinationWhitelistEnabled200Response(unittest.TestCase):
    """QueryDestinationWhitelistEnabled200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> QueryDestinationWhitelistEnabled200Response:
        """Test QueryDestinationWhitelistEnabled200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `QueryDestinationWhitelistEnabled200Response`
        """
        model = QueryDestinationWhitelistEnabled200Response()
        if include_optional:
            return QueryDestinationWhitelistEnabled200Response(
                enable_destination_whitelist = False
            )
        else:
            return QueryDestinationWhitelistEnabled200Response(
                enable_destination_whitelist = False,
        )
        """

    def testQueryDestinationWhitelistEnabled200Response(self):
        """Test QueryDestinationWhitelistEnabled200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
