# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cobo_waas2.models.swap_token import SwapToken


class TestSwapToken(unittest.TestCase):
    """SwapToken unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SwapToken:
        """Test SwapToken
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SwapToken`
        """
        model = SwapToken()
        if include_optional:
            return SwapToken(
                token_id = 'ETH_USDT',
                chain_id = 'ETH',
                asset_id = 'ETH',
                token_address = '0xdAC17F958D2ee523a2206206994597C13D831ec7',
                min_amount = '1000',
                max_amount = '100000'
            )
        else:
            return SwapToken(
                token_id = 'ETH_USDT',
                chain_id = 'ETH',
                asset_id = 'ETH',
        )
        """

    def testSwapToken(self):
        """Test SwapToken"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
