# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class AddressVerificationMethod(str, Enum):
    """
    How a self-custody address was verified. - `SIGNATURE`: Verified by off-chain wallet signature (via `Get a self-custody signature challenge` + signed message). - `SATOSHI_TEST`: Verified by an on-chain micro-deposit (via Satoshi Test challenge). 
    """

    """
    allowed enum values
    """
    SIGNATURE = 'SIGNATURE'
    SATOSHI_TEST = 'SATOSHI_TEST'

    UNKNOWN = None

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AddressVerificationMethod from a JSON string"""
        return cls(json.loads(json_str))

    @classmethod
    def _missing_(cls, value):
        return cls.UNKNOWN


