# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from cobo_waas2.models.commission_fee_detail_normalized_amount import CommissionFeeDetailNormalizedAmount
from cobo_waas2.models.settle_type import SettleType
from cobo_waas2.models.strategy_params import StrategyParams
from typing import Optional, Set
from typing_extensions import Self


class CommissionFeeDetail(BaseModel):
    """
    Commission fee detail
    """  # noqa: E501
    commission_fee_id: Optional[StrictStr] = Field(default=None, description="Unique ID of the commission fee")
    asset_id: Optional[StrictStr] = Field(default=None, description="Asset ID")
    fee_tokens: Optional[List[StrictStr]] = Field(default=None, description="List of fee token IDs")
    settle_type: Optional[SettleType] = None
    business_type_id: Optional[StrictInt] = Field(default=None, description="Unique ID of business type")
    normalized_amount: Optional[CommissionFeeDetailNormalizedAmount] = None
    strategy_id: Optional[StrictInt] = Field(default=None, description="Strategy ID")
    rule_id: Optional[StrictInt] = Field(default=None, description="Rule ID")
    strategy_params: Optional[StrategyParams] = None
    __properties: ClassVar[List[str]] = ["commission_fee_id", "asset_id", "fee_tokens", "settle_type", "business_type_id", "normalized_amount", "strategy_id", "rule_id", "strategy_params"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CommissionFeeDetail from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of normalized_amount
        if self.normalized_amount:
            _dict['normalized_amount'] = self.normalized_amount.to_dict()
        # override the default output from pydantic by calling `to_dict()` of strategy_params
        if self.strategy_params:
            _dict['strategy_params'] = self.strategy_params.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CommissionFeeDetail from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "commission_fee_id": obj.get("commission_fee_id"),
            "asset_id": obj.get("asset_id"),
            "fee_tokens": obj.get("fee_tokens"),
            "settle_type": obj.get("settle_type"),
            "business_type_id": obj.get("business_type_id"),
            "normalized_amount": CommissionFeeDetailNormalizedAmount.from_dict(obj["normalized_amount"]) if obj.get("normalized_amount") is not None else None,
            "strategy_id": obj.get("strategy_id"),
            "rule_id": obj.get("rule_id"),
            "strategy_params": StrategyParams.from_dict(obj["strategy_params"]) if obj.get("strategy_params") is not None else None
        })
        return _obj


