# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from cobo_waas2.models.payout_destination import PayoutDestination
from cobo_waas2.models.payout_mode import PayoutMode
from cobo_waas2.models.payout_rbf_type import PayoutRbfType
from cobo_waas2.models.payout_source import PayoutSource
from typing import Optional, Set
from typing_extensions import Self


class EstimateBatchPayoutFeeRequest(BaseModel):
    """
    EstimateBatchPayoutFeeRequest
    """  # noqa: E501
    token_id: StrictStr = Field(description="The ID of the cryptocurrency used for payout. ")
    payout_mode: PayoutMode
    source: PayoutSource
    destinations: List[PayoutDestination] = Field(description="The destinations of the payout.")
    rbf_type: Optional[PayoutRbfType] = None
    replaced_payout_id: Optional[StrictStr] = Field(default=None, description="The ID of the payout that this payout replaced.")
    __properties: ClassVar[List[str]] = ["token_id", "payout_mode", "source", "destinations", "rbf_type", "replaced_payout_id"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of EstimateBatchPayoutFeeRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of source
        if self.source:
            _dict['source'] = self.source.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in destinations (list)
        _items = []
        if self.destinations:
            for _item in self.destinations:
                if _item:
                    _items.append(_item.to_dict())
            _dict['destinations'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of EstimateBatchPayoutFeeRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "token_id": obj.get("token_id"),
            "payout_mode": obj.get("payout_mode"),
            "source": PayoutSource.from_dict(obj["source"]) if obj.get("source") is not None else None,
            "destinations": [PayoutDestination.from_dict(_item) for _item in obj["destinations"]] if obj.get("destinations") is not None else None,
            "rbf_type": obj.get("rbf_type"),
            "replaced_payout_id": obj.get("replaced_payout_id")
        })
        return _obj


