# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class FeeLevel(str, Enum):
    """
    The transaction fee level. Specify this property if you want Cobo to calculate the transaction fee for you based on the selected level, instead of providing the fee-related properties yourself. Possible values are: - `Slow`: A lower transaction fee, which may lead to a longer confirmation time. - `Recommended`: The recommended transaction fee, which balances the fee cost and the confirmation time. - `Fast`: A higher transaction fee for a shorter confirmation time.  You can call [Estimate transaction fee](https://www.cobo.com/developers/v2/api-references/transactions/estimate-transaction-fee) to view the estimated transaction fee of each fee level.  <Note>You cannot specify both `fee_level` and `fee` in the same request. If you specify both, the request fails.</Note>  <Note>This property does not take effect in the following cases, and the transaction fee is determined by Cobo: - The transaction uses the fixed fee model. For more information about the fee models, refer to [Fee models](https://www.cobo.com/developers/v2/guides/transactions/estimate-fees#fee-models). - The transaction is initiated from Custodial Wallets (Asset Wallets) or Exchange Wallets. </Note> 
    """

    """
    allowed enum values
    """
    SLOW = 'Slow'
    RECOMMENDED = 'Recommended'
    FAST = 'Fast'

    UNKNOWN = None

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of FeeLevel from a JSON string"""
        return cls(json.loads(json_str))

    @classmethod
    def _missing_(cls, value):
        return cls.UNKNOWN


