# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self


class GetTopUpAddress200Response(BaseModel):
    """
    GetTopUpAddress200Response
    """  # noqa: E501
    address: StrictStr = Field(description="Dedicated deposit address assigned to the specified custom_payer_id. The address is guaranteed to be unique under the same merchant and token's blockchain network (chain). ")
    payer_id: StrictStr = Field(description="Unique payer identifier on the Cobo side, auto-generated by the system. ")
    custom_payer_id: StrictStr = Field(description="Unique user identifier on the merchant side, used to assign a dedicated deposit address. ")
    merchant_id: StrictStr = Field(description="Merchant ID assigned by the system, e.g., 'M1001'. ")
    token_id: StrictStr = Field(description="The token ID for the top-up, e.g., 'ETH_USDT' refers to USDT on the Ethereum network. ")
    chain: Optional[StrictStr] = Field(default=None, description="Blockchain network identifier, e.g., 'ETH' for Ethereum, 'TRON' for Tron. ")
    developer_fee_rate: Optional[StrictStr] = Field(default=None, description="Developer fee rate for this token. For example, 0.01 represents a 1% fee. ")
    min_amount: StrictStr = Field(description="Minimum deposit amount allowed for this address. Deposits below this threshold may not be credited. ")
    created_timestamp: Optional[StrictInt] = Field(default=None, description="The created time of the payer address, represented as a UNIX timestamp in seconds.")
    updated_timestamp: Optional[StrictInt] = Field(default=None, description="The updated time of the payer address, represented as a UNIX timestamp in seconds.")
    __properties: ClassVar[List[str]] = ["address", "payer_id", "custom_payer_id", "merchant_id", "token_id", "chain", "developer_fee_rate", "min_amount", "created_timestamp", "updated_timestamp"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetTopUpAddress200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetTopUpAddress200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "address": obj.get("address"),
            "payer_id": obj.get("payer_id"),
            "custom_payer_id": obj.get("custom_payer_id"),
            "merchant_id": obj.get("merchant_id"),
            "token_id": obj.get("token_id"),
            "chain": obj.get("chain"),
            "developer_fee_rate": obj.get("developer_fee_rate"),
            "min_amount": obj.get("min_amount"),
            "created_timestamp": obj.get("created_timestamp"),
            "updated_timestamp": obj.get("updated_timestamp")
        })
        return _obj


