# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class GuardPubkeyStatus(str, Enum):
    """
    The guard binding status. Possible values include:    - `New`: The guard binding created.   - `ChangeNew`: A new guard binding created    - `WaitSelfConfirm`: The guard binding waiting user confirm on old guard.   - `WaitConfirm`: The guard binding waiting admin confirm on guard.   - `WaitActive`: The guard binding waiting active   - `Active`: The guard binding active.   - `Freeze`: The guard binding was frozen.   - `Invalid`: The guard binding was invalid. 
    """

    """
    allowed enum values
    """
    NEW = 'New'
    CHANGENEW = 'ChangeNew'
    WAITSELFCONFIRM = 'WaitSelfConfirm'
    WAITCONFIRM = 'WaitConfirm'
    WAITACTIVE = 'WaitActive'
    ACTIVE = 'Active'
    FREEZE = 'Freeze'
    INVALID = 'Invalid'

    UNKNOWN = None

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of GuardPubkeyStatus from a JSON string"""
        return cls(json.loads(json_str))

    @classmethod
    def _missing_(cls, value):
        return cls.UNKNOWN


