# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from cobo_waas2.models.payment_transaction import PaymentTransaction
from typing import Optional, Set
from typing_extensions import Self


class ListTopUpPayers200ResponseDataInner(BaseModel):
    """
    ListTopUpPayers200ResponseDataInner
    """  # noqa: E501
    merchant_id: StrictStr = Field(description="Merchant ID, e.g., \"M1001\"")
    payer_id: StrictStr = Field(description="Unique payer identifier on the Cobo side, auto-generated by the system. ")
    developer_fee_rate: StrictStr = Field(description="Developer fee rate for this token, e.g., \"0.01\" represents 1%")
    created_timestamp: Optional[StrictInt] = Field(default=None, description="The created time of the payer, represented as a UNIX timestamp in seconds.")
    updated_timestamp: Optional[StrictInt] = Field(default=None, description="The updated time of the payer, represented as a UNIX timestamp in seconds.")
    transactions: Optional[List[PaymentTransaction]] = Field(default=None, description="An array of transactions associated with this payer. Each transaction represents a separate blockchain operation related to the settlement process.")
    __properties: ClassVar[List[str]] = ["merchant_id", "payer_id", "developer_fee_rate", "created_timestamp", "updated_timestamp", "transactions"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ListTopUpPayers200ResponseDataInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in transactions (list)
        _items = []
        if self.transactions:
            for _item in self.transactions:
                if _item:
                    _items.append(_item.to_dict())
            _dict['transactions'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ListTopUpPayers200ResponseDataInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "merchant_id": obj.get("merchant_id"),
            "payer_id": obj.get("payer_id"),
            "developer_fee_rate": obj.get("developer_fee_rate"),
            "created_timestamp": obj.get("created_timestamp"),
            "updated_timestamp": obj.get("updated_timestamp"),
            "transactions": [PaymentTransaction.from_dict(_item) for _item in obj["transactions"]] if obj.get("transactions") is not None else None
        })
        return _obj


