# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List
from typing_extensions import Annotated
from cobo_waas2.models.merchant_kyc_address import MerchantKycAddress
from cobo_waas2.models.merchant_kyc_person_attachment import MerchantKycPersonAttachment
from typing import Optional, Set
from typing_extensions import Self


class MerchantKycPersonInfo(BaseModel):
    """
    MerchantKycPersonInfo
    """  # noqa: E501
    name: Annotated[str, Field(strict=True, max_length=64)] = Field(description="The name or title of an identification document.")
    name_en: Annotated[str, Field(strict=True, max_length=64)] = Field(description="The English-language equivalent of the identification document's name.")
    id_number: Annotated[str, Field(strict=True, max_length=64)] = Field(description="The unique identification number associated with the identification document.")
    date_of_birth: Annotated[str, Field(strict=True, max_length=64)] = Field(description="The date of birth of the individual, usually in the format YYYYMMDD. ")
    issue_date: Annotated[str, Field(strict=True, max_length=64)] = Field(description="The issue date refers to the date when a document, such as an identification card or passport, was officially issued or granted, usually in the format YYYYMMDD. ")
    expiration_date: Annotated[str, Field(strict=True, max_length=64)] = Field(description="The expiration date refers to the date when a document, such as an identification card or passport, is no longer valid or legally usable, usually in the format YYYYMMDD. ")
    attachments: List[MerchantKycPersonAttachment] = Field(description="Additional files or documents associated with a message or record to provide extra information or context. ")
    residential_address: MerchantKycAddress
    __properties: ClassVar[List[str]] = ["name", "name_en", "id_number", "date_of_birth", "issue_date", "expiration_date", "attachments", "residential_address"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MerchantKycPersonInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in attachments (list)
        _items = []
        if self.attachments:
            for _item in self.attachments:
                if _item:
                    _items.append(_item.to_dict())
            _dict['attachments'] = _items
        # override the default output from pydantic by calling `to_dict()` of residential_address
        if self.residential_address:
            _dict['residential_address'] = self.residential_address.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MerchantKycPersonInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "name_en": obj.get("name_en"),
            "id_number": obj.get("id_number"),
            "date_of_birth": obj.get("date_of_birth"),
            "issue_date": obj.get("issue_date"),
            "expiration_date": obj.get("expiration_date"),
            "attachments": [MerchantKycPersonAttachment.from_dict(_item) for _item in obj["attachments"]] if obj.get("attachments") is not None else None,
            "residential_address": MerchantKycAddress.from_dict(obj["residential_address"]) if obj.get("residential_address") is not None else None
        })
        return _obj


