# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class MerchantKycCompanyAttachmentFileType(str, Enum):
    """
    The company attachment file type.
    """

    """
    allowed enum values
    """
    BI = 'BI'
    BR = 'BR'
    CI = 'CI'
    NNC1 = 'NNC1'
    NAR = 'NAR'
    SSC = 'SSC'
    AOA = 'AOA'
    OTHER = 'Other'
    BAP = 'BAP'
    ANNUAL_RETURN = 'ANNUAL_RETURN'
    PLATFORM_SCREENSHOT = 'PLATFORM_SCREENSHOT'
    BUSINESS_DOCUMENT = 'BUSINESS_DOCUMENT'

    UNKNOWN = None

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of MerchantKycCompanyAttachmentFileType from a JSON string"""
        return cls(json.loads(json_str))

    @classmethod
    def _missing_(cls, value):
        return cls.UNKNOWN


