# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class PaymentSubscriptionActionStatus(str, Enum):
    """
    The current status of a subscription action. - `Pending`: The subscription action has been created and is awaiting processing. - `Processing`: The subscription action is being processed. - `Completed`: The subscription action success. - `Failed`: The subscription action could not be completed due to an error. 
    """

    """
    allowed enum values
    """
    PENDING = 'Pending'
    PROCESSING = 'Processing'
    COMPLETED = 'Completed'
    FAILED = 'Failed'

    UNKNOWN = None

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PaymentSubscriptionActionStatus from a JSON string"""
        return cls(json.loads(json_str))

    @classmethod
    def _missing_(cls, value):
        return cls.UNKNOWN


