# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class PaymentSubscriptionStatus(str, Enum):
    """
    The current status of a subscription action. - `Pending`: The subscription has been created and is awaiting approve. - `WaitingApproval`: The subscription approve transaction is create and is awaiting transaction completed. - `Approved`: The subscription has been approved and is waiting subscript . - `Processing`: The subscription subscript transaction is create and is awaiting transaction completed. - `Active`: The subscription is active. - `InsufficientApproval`: The subscription is insufficient approval. - `Paused`: The subscription is paused. - `Ended`: The subscription is ended. - `Canceled`: The subscription is canceled. - `Failed`: The subscription is failed. 
    """

    """
    allowed enum values
    """
    PENDING = 'Pending'
    WAITINGAPPROVAL = 'WaitingApproval'
    APPROVED = 'Approved'
    PROCESSING = 'Processing'
    ACTIVE = 'Active'
    INSUFFICIENTAPPROVAL = 'InsufficientApproval'
    PAUSED = 'Paused'
    ENDED = 'Ended'
    CANCELED = 'Canceled'
    FAILED = 'Failed'

    UNKNOWN = None

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PaymentSubscriptionStatus from a JSON string"""
        return cls(json.loads(json_str))

    @classmethod
    def _missing_(cls, value):
        return cls.UNKNOWN


