# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class PaymentSubscriptionPeriodType(str, Enum):
    """
    Specifies the period of charge for the subscription plan: - `Yearly`: The subscription period of charge is one year. - `Quarterly`: The subscription period of charge is one quarter. - `Monthly`: The subscription period of charge is one month. 
    """

    """
    allowed enum values
    """
    YEARLY = 'Yearly'
    QUARTERLY = 'Quarterly'
    MONTHLY = 'Monthly'

    UNKNOWN = None

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PaymentSubscriptionPeriodType from a JSON string"""
        return cls(json.loads(json_str))

    @classmethod
    def _missing_(cls, value):
        return cls.UNKNOWN


