# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from cobo_waas2.models.payment_bank_withdrawal_status import PaymentBankWithdrawalStatus
from typing import Optional, Set
from typing_extensions import Self


class PaymentBankWithdrawal(BaseModel):
    """
    PaymentBankWithdrawal
    """  # noqa: E501
    bank_withdrawal_id: StrictStr = Field(description="The bank withdrawal ID generated by Cobo.")
    request_id: StrictStr = Field(description="The request ID provided by you when creating the bank withdrawal.")
    source_bank_account_id: StrictStr = Field(description="The source bank account ID. The destination bank account must be tagged as `VA`. ")
    target_bank_account_id: StrictStr = Field(description="The target bank account ID that receives the bank withdrawal.")
    currency: StrictStr = Field(description="The fiat currency of the bank withdrawal.")
    amount: StrictStr = Field(description="The bank withdrawal amount.")
    remark: Optional[StrictStr] = Field(default=None, description="The remark for the bank withdrawal.")
    status: PaymentBankWithdrawalStatus
    created_timestamp: StrictInt = Field(description="The creation time of the bank withdrawal, represented as a UNIX timestamp in seconds.")
    failed_reason: Optional[StrictStr] = Field(default=None, description="The reason why the bank withdrawal failed.")
    __properties: ClassVar[List[str]] = ["bank_withdrawal_id", "request_id", "source_bank_account_id", "target_bank_account_id", "currency", "amount", "remark", "status", "created_timestamp", "failed_reason"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PaymentBankWithdrawal from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PaymentBankWithdrawal from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "bank_withdrawal_id": obj.get("bank_withdrawal_id"),
            "request_id": obj.get("request_id"),
            "source_bank_account_id": obj.get("source_bank_account_id"),
            "target_bank_account_id": obj.get("target_bank_account_id"),
            "currency": obj.get("currency"),
            "amount": obj.get("amount"),
            "remark": obj.get("remark"),
            "status": obj.get("status"),
            "created_timestamp": obj.get("created_timestamp"),
            "failed_reason": obj.get("failed_reason")
        })
        return _obj


