# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class PaymentBulkSendItemStatus(str, Enum):
    """
    The current status of the bulk send item. Possible values include: - `Pending`: The bulk send item has been created and is waiting to be processed. - `Processing`: The bulk send item is currently being processed and the transfer is in progress. - `Completed`: The bulk send item has been successfully processed and the funds have been transferred. - `Failed`: The bulk send item was submitted for on-chain transfer, but the transfer attempt failed (for example, the batch payout could not be created, or the payout transaction failed, was rejected, or timed out). A transfer was attempted but the funds were not delivered; the locked amount is released and the commission fee is refunded. This is a terminal state. Resubmit the item to retry. - `NotExecuted`: The bulk send item was never submitted for on-chain transfer; it was skipped before any attempt. This happens when the item fails pre-execution (address or compliance) validation; or, in `Strict` execution mode, when any other item in the batch fails validation (in `Strict` mode all items become `NotExecuted` if one fails); or when an upstream step (fund sweep or commission fee charge) fails. No funds were moved and the locked amount is released. This is a terminal state. Fix the issue and resubmit the item to retry. 
    """

    """
    allowed enum values
    """
    PENDING = 'Pending'
    PROCESSING = 'Processing'
    COMPLETED = 'Completed'
    FAILED = 'Failed'
    NOTEXECUTED = 'NotExecuted'

    UNKNOWN = None

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PaymentBulkSendItemStatus from a JSON string"""
        return cls(json.loads(json_str))

    @classmethod
    def _missing_(cls, value):
        return cls.UNKNOWN


