# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from cobo_waas2.models.payout_destination_detail import PayoutDestinationDetail
from cobo_waas2.models.payout_source import PayoutSource
from cobo_waas2.models.payout_status import PayoutStatus
from typing import Optional, Set
from typing_extensions import Self


class PayoutDetail(BaseModel):
    """
    PayoutDetail
    """  # noqa: E501
    payout_id: StrictStr = Field(description="The payout ID.")
    source: Optional[PayoutSource] = None
    destination_count: StrictInt = Field(description="The destination count.")
    token_id: StrictStr = Field(description="The token ID.")
    total_amount: StrictStr = Field(description="The total amount.")
    status: PayoutStatus
    description: Optional[StrictStr] = Field(default=None, description="The description.")
    created_timestamp: StrictInt = Field(description="The created time of the payout, represented as a UNIX timestamp in seconds.")
    updated_timestamp: Optional[StrictInt] = Field(default=None, description="The updated time of the payout, represented as a UNIX timestamp in seconds.")
    destinations: Optional[List[PayoutDestinationDetail]] = Field(default=None, description="The destinations of the payout.")
    __properties: ClassVar[List[str]] = ["payout_id", "source", "destination_count", "token_id", "total_amount", "status", "description", "created_timestamp", "updated_timestamp", "destinations"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PayoutDetail from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of source
        if self.source:
            _dict['source'] = self.source.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in destinations (list)
        _items = []
        if self.destinations:
            for _item in self.destinations:
                if _item:
                    _items.append(_item.to_dict())
            _dict['destinations'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PayoutDetail from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "payout_id": obj.get("payout_id"),
            "source": PayoutSource.from_dict(obj["source"]) if obj.get("source") is not None else None,
            "destination_count": obj.get("destination_count"),
            "token_id": obj.get("token_id"),
            "total_amount": obj.get("total_amount"),
            "status": obj.get("status"),
            "description": obj.get("description"),
            "created_timestamp": obj.get("created_timestamp"),
            "updated_timestamp": obj.get("updated_timestamp"),
            "destinations": [PayoutDestinationDetail.from_dict(_item) for _item in obj["destinations"]] if obj.get("destinations") is not None else None
        })
        return _obj


