# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ReportStatus(str, Enum):
    """
    The status of the report. - `Processing`: The report is being generated. - `Completed`: The report has been completed. - `Failed`: The report has failed. 
    """

    """
    allowed enum values
    """
    PROCESSING = 'Processing'
    COMPLETED = 'Completed'
    FAILED = 'Failed'

    UNKNOWN = None

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ReportStatus from a JSON string"""
        return cls(json.loads(json_str))

    @classmethod
    def _missing_(cls, value):
        return cls.UNKNOWN


