# coding: utf-8

"""
    Cobo Wallet as a Service 2.0

    Contact: help@cobo.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class SkipCheckType(str, Enum):
    """
    The skip check type. Possible values include:   - `OnchainFeeBalance`: The system does not verify whether the balance is sufficient to pay the on-chain transaction fees; currently, this only applies to the TRON chain for MPC and Custodial Web3 wallets. 
    """

    """
    allowed enum values
    """
    ONCHAINFEEBALANCE = 'OnchainFeeBalance'

    UNKNOWN = None

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SkipCheckType from a JSON string"""
        return cls(json.loads(json_str))

    @classmethod
    def _missing_(cls, value):
        return cls.UNKNOWN


